{
 "title": "Akamai Known Bots",
 "description": "Information about Akamai known bots ",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "table",
    "query": "SELECT CONCAT((SELECT name FROM system.databases),'.', 'siem')"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "SELECT host\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nGROUP BY host\nORDER BY host\nLIMIT 100"
   },
   {
    "name": "akamai_bots",
    "label": "Akamai Known Bots",
    "query": "SELECT\nmessage\nFROM ${table}\nARRAY JOIN ruleMessages as message, ruleTags as tag\nWHERE $__timeFilter(timestamp)\nAND tag =  'AKAMAI/BOT/AKAMAI_CATEGORIZED'\nGROUP BY message, tag\nORDER BY count(*) DESC\nLIMIT 10"
   },
   { "name": "limit", "label": "Limit", "query": "1,2,3,4,5,6,7,8,9,10" },
   {
    "name": "bad_reputation_client",
    "label": "Reputation",
    "query": "SELECT toString(clientIP)\nFROM ${table}\nWHERE $__timeFilter(timestamp) \nAND has(ruleTags, 'REPUTATION')\nGROUP BY clientIP\nORDER BY count() DESC\nLIMIT 10"
   }
  ]
 },
 "panels": [
  { "title": "Akamai Known Bots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All Akamai Known Bots req. over Time per host",
   "type": "timeseries",
   "description": "Akamai Known Bots req. over time per host with the top ${limit} hosts.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT host, count(), $__timeInterval(timestamp) as time\nFROM ${table}\n  WHERE $__timeFilter(timestamp)\n  AND has(ruleTags, 'AKAMAI/BOT/AKAMAI_CATEGORIZED')\n  AND $__conditionalAll(host IN (${host:sqlstring}), $host)\n  GROUP BY time, host\n  ORDER BY time, count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - knownbots - ${__user.login}'"
    }
   ]
  },
  {
   "title": "All Akamai Known Bots req. per host - Host(s): ${host}",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT host, count(host)\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND has(ruleTags, 'AKAMAI/BOT/AKAMAI_CATEGORIZED')\nAND $__conditionalAll(host IN (${host:sqlstring}), $host)\nGROUP BY host\nORDER BY count(host) DESC\nLIMIT ${limit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - akamaibotreqoverimte - ${__user.login}'"
    }
   ]
  },
  {
   "title": "Akamai Known Bot: $akamai_bots req. - Host(s): ${host}",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nruleData[1] as bot, count(bot) as bots\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND $__conditionalAll(arrayJoin(ruleMessages) IN (${akamai_bots:sqlstring}), $akamai_bots)\nAND $__conditionalAll(host IN (${host:sqlstring}), $host)\nGROUP BY bot\nORDER BY count(bot) DESC\nLIMIT 10\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - knownbotsgroups - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Akamai Known Bots - Host: ${host}",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nmessage,  count(tag)\nFROM ${table}\nARRAY JOIN ruleMessages as message, ruleTags as tag\nWHERE $__timeFilter(timestamp)\nAND tag = 'AKAMAI/BOT/AKAMAI_CATEGORIZED'\nAND $__conditionalAll(host IN (${host:sqlstring}), $host)\nGROUP BY message, tag\nORDER BY count(tag) DESC\nLIMIT 10\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - statuscode - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "${akamai_bots} req. over Time for host: ${host} ",
   "type": "timeseries",
   "description": "${akamai_bots} req. for all or a select group of hosts over time.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT ruleData[1] as bot, count(*), $__timeInterval(timestamp) as time\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND has(ruleTags, 'AKAMAI/BOT/AKAMAI_CATEGORIZED')\nAND $__conditionalAll(host IN (${host:sqlstring}), $host)\nAND $__conditionalAll(arrayJoin(ruleMessages) IN (${akamai_bots:sqlstring}), $akamai_bots)\nGROUP BY bot, time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - botgroupovertime - ${__user.login}'"
    }
   ]
  }
 ]
}