{
 "title": "Akamai Images",
 "time": { "from": "now-7d", "to": "now-1m" },
 "templating": {
  "list": [
   {
    "name": "reqHost",
    "label": "Host",
    "query": "SELECT\nreplaceRegexpOne(lcase(reqHost), ':\\d*$', '')\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND statusCode = 404\nGROUP BY reqHost\nORDER BY reqHost\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - 403hosts - ${__user.login}'"
   },
   {
    "name": "table",
    "query": "SELECT CONCAT((SELECT name FROM system.databases),'.', 'logs')"
   },
   {
    "name": "database",
    "query": "SELECT name FROM system.databases"
   },
   { "name": "content", "label": "content", "query": "image" },
   { "name": "interval", "label": "interval", "query": "${VAR_INTERVAL}" }
  ]
 },
 "panels": [
  {
   "title": "Total image bytes/hits per day",
   "type": "timeseries",
   "description": "Get the total amount of bytes served just for the objects with an image content type. Interval stored as a var in the dashboard and fixed via relative time in query options.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "/*\nUsing UTC by default, you can set specific timezone in toStartOfInterval() if required\n*/\nSELECT toStartOfInterval(toDateTime(reqTimeSec), INTERVAL 1 DAY) AS time, sum(rspContentLen) as bytes, count() as hits\nFROM ${table}\nWHERE $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND reqTimeSec >= date_sub(day, ${interval}, today())\nAND rspContentType LIKE 'image/%'\nGROUP BY time\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - images_bytes_per_day - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Bytes per image type",
   "type": "bargauge",
   "description": "Filtering on all objects that have a content-type of image/* and grouping based on specific image format.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/*\n\n*/\nSELECT splitByChar('/',assumeNotNull(rspContentType))[2] as contentType, sum(rspContentLen) as contentLength, count(*) as hits\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND rspContentType IS NOT NULL\nAND rspContentType LIKE 'image/%'\nGROUP BY contentType\nORDER BY contentLength DESC\nLIMIT 10\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - 404resp - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "hits per image content type over time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 29 }
   ]
  },
  {
   "title": "Top 50 largest images",
   "type": "table",
   "description": "Lookup objects with a content-type which contains/images and sort on the response content-size. If it's just a single hit, image object is probably already optimized by Akamai Image Manager.",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "/*\n*/\nSELECT rspContentLen as size,  count(*) as hits, sum(rspContentLen) as total, reqHost, splitByChar('/',assumeNotNull(rspContentType))[2] as contentType, reqPath\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND rspContentType LIKE 'image/%'\nGROUP BY reqHost, size, reqPath, contentType\nORDER BY size DESC\nLIMIT 50\nSETTINGS hdx_query_max_execution_time=60, hdx_query_max_peers=2, hdx_query_admin_comment='akamai - 404resp - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "options": {
    "content": "# Large Images\n\nPeople make mistakes, that makes us human 😉. But sending images with a *content-length* of a couple of MBs is a very, very **bad** idea.\nIt will negatively impact the performance of your site and you are just waisting resources. 🚮\n\n[Akamai Image and Video Manager (IVM)](https://www.akamai.com/products/image-and-video-manager) can help you by automatically optimizing your images and serve them in next-gen formats like [webp](https://developers.google.com/speed/webp) \nand [avif](https://en.wikipedia.org/wiki/AVIF). \n\nSo if somebody is uploading images of 50MB, again 😡. Don't worry, IVM will automatically optimize and enhance your images.\n"
   }
  },
  { "title": "Annotations", "type": "annolist", "gridPos": { "h": 4, "w": 8, "x": 16, "y": 32 } },
  {
   "title": "total image bytes served for the top-5 image types per $__interval",
   "type": "timeseries",
   "description": "We first lookup the most active image types based on type for the last your and we're only going to filter on those image types. As graph was unreadable we're only showing the total image bytes served over time. Doing this lookup just once and reusing the data in other visualization.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "/*\nLet's first get the most acive image types from the last 1 hour\nAnd use the result as other select statement to get them per time interval.\n*/\nWITH top5_image_types AS (\n  SELECT splitByChar('/',assumeNotNull(rspContentType))[2] as contentType, sum(rspContentLen) as bytes\n  FROM ${table}\n  WHERE reqTimeSec >= date_sub(hour, 1, now())\n  AND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\n  AND rspContentType LIKE 'image/%'\n  GROUP BY contentType\n  ORDER BY bytes DESC\n  LIMIT 5\n) \nSELECT  $__timeInterval(reqTimeSec) as time, splitByChar('/',assumeNotNull(rspContentType))[2] as contentType, count(*) as hits, sum(rspContentLen) as bytes\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND contentType IN (SELECT contentType FROM top5_image_types)\n/*\nTesting a grouping set. We're creating two groups, one with the image types and a total per timeinterval.\nAs the bytes per image type was not very usefull created a separate group with the total hits.\nThere is another visualisation using the output from this single query.\n*/\nGROUP BY \n  GROUPING SETS(\n\t\t(time, contentType),\n\t\t(time)\n\t\t)\nORDER BY time, hits\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - image - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Hits per image type",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Hits per image type",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Total image type bytes delivered per day for the last $interval days",
   "type": "barchart",
   "description": "Get the total amount of bytes served just for the objects with an image content type. Interval stored as a var in the dashboard.",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "\nSELECT toStartOfInterval(toDateTime(reqTimeSec), INTERVAL 1 DAY) AS time, sum(rspContentLen) as bytes\nFROM ${table}\nWHERE $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND reqTimeSec >= date_sub(day, ${interval}, today())\nAND rspContentType LIKE 'image/%'\nGROUP BY time\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - images_bytes_per_day - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "total hits per image type over time",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 29 }
   ]
  }
 ]
}