{
 "title": "Usage Report",
 "description": "Report on Ingest data",
 "time": { "from": "2024-03-19T14:39:17.149Z", "to": "2024-04-03T08:36:41.753Z" },
 "templating": {
  "list": [
   {
    "name": "table",
    "query": "SELECT concat(project,'.',name) as table FROM (SELECT database as project, name FROM system.tables WHERE engine = 'TurbineStorage' AND (project != 'sample_project'  AND project != 'hdx'))"
   },
   {
    "name": "catalog",
    "query": "SELECT concat(project,'.`',table,'#.catalog`')\nFROM (SELECT splitByChar('.','${table}')[1] as project, splitByChar('.','${table}')[2] as table)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Number of partitions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    count(rows) as partitions\n    FROM ${catalog}\n    WHERE $__timeFilter(min_timestamp)"
    }
   ]
  },
  {
   "title": "Total Number of logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    sum(rows) as logs\n    FROM ${catalog}\n    WHERE $__timeFilter(min_timestamp)"
    }
   ]
  },
  {
   "title": "Data Footprint in Trafficpeak",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    sum(index_size + manifest_size + data_size) as trafficpeak_size\n    FROM ${catalog}\n    WHERE $__timeFilter(min_timestamp)"
    }
   ]
  },
  {
   "title": "Raw Data Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    sum(raw_size) as incoming_data\n    FROM ${catalog}\n    WHERE $__timeFilter(min_timestamp)"
    }
   ]
  },
  {
   "title": "Number of logs per day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfDay(min_timestamp) as time,\n    sum(rows) as logs\n    FROM ${catalog}\n    WHERE $__timeFilter(min_timestamp)\n    GROUP BY time\n    ORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Data Size per day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfDay(min_timestamp) as time,\n    sum(index_size + manifest_size + data_size) as trafficpeak_size,\n    sum(raw_size) as raw_data\n    FROM ${catalog}\n    WHERE $__timeFilter(min_timestamp)\n    GROUP BY time\n    ORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Usage Report",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfDay(min_timestamp) as day,\n    sum(rows) as logs,\n    sum(index_size + manifest_size + data_size) as trafficpeak_size,\n    sum(raw_size) as raw_data\n    FROM ${catalog}\n    WHERE $__timeFilter(min_timestamp)\n    GROUP BY day\n    ORDER BY day DESC",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Number of Partitions per day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfDay(min_timestamp) as time,\n    count(rows) as partitions\n    FROM ${catalog}\n    WHERE $__timeFilter(min_timestamp)\n    GROUP BY time\n    ORDER BY time DESC"
    }
   ]
  }
 ]
}