{
 "title": "Akamai Client Reputation",
 "description": "Akamai SIEM powered by Hydrolix dashboard for security analytics\r\n",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "table",
    "query": "SELECT CONCAT((SELECT name FROM system.databases),'.', 'siem')"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "SELECT host\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nGROUP BY host\nORDER BY host\nLIMIT 100"
   },
   { "name": "limit", "label": "ClientIP Limit", "query": "1,2,3,4,5,6,7,8,9,10" },
   {
    "name": "bad_reputation_client",
    "label": "Reputation",
    "query": "SELECT toString(clientIP)\nFROM ${table}\nWHERE $__timeFilter(timestamp) \nAND has(ruleTags, 'REPUTATION')\nGROUP BY clientIP\nORDER BY count() DESC\nLIMIT 10"
   }
  ]
 },
 "panels": [
  { "title": "Client Reputation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Client Reputation req. over Time per host",
   "type": "timeseries",
   "description": "Akamai Known Bots req. over time per host with the top ${limit} hosts.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT host, count(), $__timeInterval(timestamp) as time\nFROM ${table}\n  WHERE $__timeFilter(timestamp)\n  AND has(ruleTags, 'REPUTATION')\n  AND $__conditionalAll(host IN (${host:sqlstring}), $host)\n  GROUP BY time, host\n  ORDER BY time, count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - statuscode - ${__user.login}'"
    }
   ]
  },
  {
   "title": "Client Rep. score for a client ${bad_reputation_client} per group per ${__interval}",
   "type": "timeseries",
   "description": "Show the client reputation score  per group for a single IP over a selected period of time per day.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, \nsplitByChar('=', assumeNotNull(data))[1] AS reputation_group,\ntoInt8(splitByChar('=', assumeNotNull(data))[2]) AS reputation_score, clientIP\nFROM ${table}\nARRAY JOIN ruleData as data, ruleTags as tag\n  WHERE $__timeFilter(timestamp)\n  AND tag = 'REPUTATION'  \n  AND isNotNull(data)\n  AND length(ruleTags) = length(ruleData)\n  AND $__conditionalAll(clientIP IN (${bad_reputation_client:sqlstring}), $clientIP)\n  AND $__conditionalAll(host IN (${host:sqlstring}), $host)\n  GROUP BY time, reputation_group, reputation_score, clientIP\n  ORDER BY time, reputation_group, reputation_score\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - clientrep - ${__user.login}'"
    }
   ]
  },
  {
   "title": "Top ${limit} hosts with a bad reputation by # of req.",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT clientIP, count(*) as total_requests\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND has(ruleTags, 'REPUTATION')\nAND $__conditionalAll(host IN (${host:sqlstring}), $host)\nGROUP BY clientIP\nORDER BY total_requests DESC\nLIMIT ${limit}\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - statuscode - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Client Reputation - per host",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\ncount(tag), host\nFROM ${table}\nARRAY JOIN ruleMessages as message, ruleTags as tag\nWHERE $__timeFilter(timestamp)\nAND tag = 'REPUTATION'\nAND $__conditionalAll(host IN (${host:sqlstring}), $host)\nGROUP BY host\nORDER BY count(tag) DESC\nLIMIT 200\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - statuscode - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Client Reputation - policies",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nmessage,  count(tag)\nFROM ${table}\nARRAY JOIN ruleMessages as message, ruleTags as tag\nWHERE $__timeFilter(timestamp)\nAND tag = 'REPUTATION'\nAND $__conditionalAll(host IN (${host:sqlstring}), $host)\nGROUP BY message\nORDER BY count(tag) DESC\nLIMIT 200\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - statuscode - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Client Reputation - Request per reputation group",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\nsplitByChar('=', assumeNotNull(data))[1] AS reputation_group,\ncount()\nFROM ${table}\n/* \nThere are situations where the ruleData and ruleTags are uneven in length.\nWe've seen this when a ruleTags array contains the 'AKAMAI/WAF/PENALTYBOX' tag. This tag doesn't have a corresponding ruleData.\nIf array's are incomplete the JOIN will fail. So a test with removing that specific entry from the ruleTags array so the are even in size again.\n-- ARRAY JOIN ruleData as data, ruleTags as tag\n*/ \nARRAY JOIN ruleData as data, if(length(ruleTags) != length(ruleData), arrayFilter(x -> x NOT LIKE 'AKAMAI/WAF/PENALTYBOX', ruleTags), ruleTags) as tag\nWHERE $__timeFilter(timestamp)\n-- First only filter on ruleTags that have reputation, then use ARRAY JOIN results to only filter REPUTATION entriesa\nAND has(ruleTags, 'REPUTATION')\nAND tag = 'REPUTATION'\n/*\nIn case arrayFilter function is not working, use length to only filter even ruleData/ruleTags so ARRAY JOIN is working correctly.\n--AND length(ruleTags) != length(ruleData)\n*/\nGROUP BY reputation_group\nORDER BY count() DESC\nLIMIT 5",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Client Reputation - Request per reputation group - previous interval period until ${__from:date:YYYY-MM-DD HH:mm:ss}",
   "type": "bargauge",
   "description": "The TimV special to show previous period.\nEnd date is  ${__from:date:YYYY-MM-DD HH:mm:ss} and start time is '(start time - interval).",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nsplitByChar('=', assumeNotNull(data))[1] AS reputation_group,\ncount()\nFROM ${table}\n/* \nThere are situations where the ruleData and ruleTags are uneven in length.\nWe've seen this when a ruleTags array contains the 'AKAMAI/WAF/PENALTYBOX' tag. This tag doesn't have a corresponding ruleData.\nIf array's are incomplete the JOIN will fail. So a test with removing that specific entry from the ruleTags array so the are even in size again.\n-- ARRAY JOIN ruleData as data, ruleTags as tag\n*/ \nARRAY JOIN ruleData as data, if(length(ruleTags) != length(ruleData), arrayFilter(x -> x NOT LIKE 'AKAMAI/WAF/PENALTYBOX', ruleTags), ruleTags) as tag\nWHERE timestamp >= toDateTime(${__from:date:seconds} - (${__to:date:seconds} - ${__from:date:seconds})) AND timestamp <= ${__from:date:seconds}\n-- First only filter on ruleTags that have reputation, then use ARRAY JOIN results to only filter REPUTATION entriesa\nAND has(ruleTags, 'REPUTATION')\nAND tag = 'REPUTATION'\n/*\nIn case arrayFilter function is not working, use length to only filter even ruleData/ruleTags so ARRAY JOIN is working correctly.\n--AND length(ruleTags) != length(ruleData)\n*/\nGROUP BY reputation_group\nORDER BY count() DESC\nLIMIT 5",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Client Reputation - Req. per Reputation scores group",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n/*\ndata will have format of SCANTL=10 for example\nand we have to assume it's not null as splitbychar will file otherwise.\n*/\nsplitByChar('=', assumeNotNull(data))[1] AS reputation_group,\nsplitByChar('=', assumeNotNull(data))[2] AS reputation_score,\ncount()\nFROM ${table}/* \nThere are situations where the ruleData and ruleTags are uneven in length.\nWe've seen this when a ruleTags array contains the 'AKAMAI/WAF/PENALTYBOX' tag. This tag doesn't have a corresponding ruleData.\nIf array's are incomplete the JOIN will fail. So a test with removing that specific entry from the ruleTags array so the are even in size again.\n-- ARRAY JOIN ruleData as data, ruleTags as tag\n*/ \nARRAY JOIN ruleData as data, if(length(ruleTags) != length(ruleData), arrayFilter(x -> x NOT LIKE 'AKAMAI/WAF/PENALTYBOX', ruleTags), ruleTags) as tag\nWHERE $__timeFilter(timestamp)\n-- First only filter on ruleTags that have reputation, then use ARRAY JOIN results to only filter REPUTATION entriesa\nAND has(ruleTags, 'REPUTATION')\nAND tag = 'REPUTATION'\n/*\nIn case arrayFilter function is not working, use length to only filter even ruleData/ruleTags so ARRAY JOIN is working correctly.\n--AND length(ruleTags) != length(ruleData)\n*/\nGROUP BY reputation_group, reputation_score\nORDER BY reputation_group, count() DESC, reputation_score DESC\nLIMIT 3 by reputation_group\nLIMIT 50\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - repscores - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Client Reputation req. over time per reputation group.",
   "type": "timeseries",
   "description": "Akamai Known Bots req. over time per host with the top ${limit} hosts.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\nsplitByChar('=', assumeNotNull(data))[1] AS reputation_group, count(), $__timeInterval(timestamp) as time\n\nFROM ${table}\n/* \nThere are situations where the ruleData and ruleTags are uneven in length.\nWe've seen this when a ruleTags array contains the 'AKAMAI/WAF/PENALTYBOX' tag. This tag doesn't have a corresponding ruleData.\nIf array's are incomplete the JOIN will fail. So a test with removing that specific entry from the ruleTags array so the are even in size again.\n-- ARRAY JOIN ruleData as data, ruleTags as tag\n*/ \nARRAY JOIN ruleData as data, if(length(ruleTags) != length(ruleData), arrayFilter(x -> x NOT LIKE 'AKAMAI/WAF/PENALTYBOX', ruleTags), ruleTags) as tag\nWHERE $__timeFilter(timestamp)\n-- First only filter on ruleTags that have reputation, then use ARRAY JOIN results to only filter REPUTATION entriesa\nAND has(ruleTags, 'REPUTATION')\nAND tag = 'REPUTATION'\n/*\nIn case arrayFilter function is not working, use length to only filter even ruleData/ruleTags so ARRAY JOIN is working correctly.\n--AND length(ruleTags) != length(ruleData)\n*/\nGROUP BY reputation_group, time\nORDER BY time, count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - repscoreovertime - ${__user.login}'"
    }
   ]
  }
 ]
}