{
 "title": "Akamai Uncached hits",
 "time": { "from": "now-6h", "to": "now-1m" },
 "templating": {
  "list": [
   {
    "name": "reqHost",
    "label": "Host",
    "query": "SELECT\n    reqHost\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND rspContentType IN (${content_type})\nAND statusCode = 200\nGROUP BY reqHost\nORDER BY reqHost\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - page-hits - ${__user.login}'"
   },
   {
    "name": "table",
    "query": "SELECT CONCAT((SELECT name FROM system.databases),'.', 'logs')"
   },
   { "name": "content_type", "query": "${VAR_CONTENT_TYPE}" },
   { "name": "limit", "label": "limit", "query": "3" }
  ]
 },
 "panels": [
  {
   "title": "200 resp. over time for uncached items with interval of $__interval for period: ${__from:date:YYYY-MM-DD-HH-mm} - ${__to:date:YYYY-MM-DD-HH-mm} for content types NOT being ${content_type}",
   "type": "timeseries",
   "description": "Number of hits on objects that could potentially be cached. They have a cacheStatus of 0 but are not part of certain content types and are hit more than once. ",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "/*\nUsing a Common Table Expressions (CTA) (WITH) to first to limit on the number of hosts.\nSo let's calculate to total over the select timefilter and use the found hosts in other where statement\n\nWe also need to use REPLACE to cleanup hosts to use :443 as reqHost\n*/\nWITH most_active_hosts AS \n(\n\tSELECT REPLACE(reqHost, ':443', '') as host, SUM(rspContentLen) as totalBytes\n\tFROM ${table}\n\tWHERE $__timeFilter(reqTimeSec)\n\tAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\n  AND rspContentType NOT IN (${content_type})\n\tAND statusCode = 200\n\tAND cacheStatus = 0\n\tAND reqHost IS NOT NULL\n\tGROUP BY host\n\tORDER BY totalBytes DESC\n\tLIMIT ${limit}\n)\nSELECT $__timeInterval(reqTimeSec) as time, count(*) as hits, REPLACE(reqHost, ':443', '') as host, SUM(rspContentLen) as totalBytes\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND rspContentType NOT IN (${content_type})\nAND statusCode = 200\nAND cacheStatus = 0\nAND reqHost IN (SELECT host FROM most_active_hosts)\nGROUP BY host, time \nHAVING hits > 1\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - uncached objects - ${__user.login}'",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Total Cache Misses for period: ${__from:date:YYYY-MM-DD-HH-mm} - ${__to:date:YYYY-MM-DD-HH-mm}",
   "type": "table",
   "description": "Cache misses for files that can be potentially be cached.",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "/*\nLet's lookup files that have a cacheStatus of 0.\n*/\nSELECT reqHost as host, reqPath as path, cacheable, count(*) as hits, SUM(rspContentLen) as totalBytes\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND rspContentType NOT IN (${content_type})\nAND statusCode = 200\nAND cacheStatus = 0\nGROUP BY host, path, cacheable\nHAVING hits > 1\nORDER BY hits DESC\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - uncachedObjects - ${__user.login}'",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Caching info",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "options": {
    "content": "# Akamai Caching\n\nThere can be objects that are *potentially* cacheable but have a cacheStatus=0. \nThis might be done on purpose, a TTL that's too short, a Vary header stopping Akamai from caching the object, or just some configuration/caching setup problem.\n\n**Cache is king** 👑, so try to cache as much as possible.\n\n* [Learn about Akamai's caching](https://techdocs.akamai.com/property-mgr/docs/know-caching)\n* [Caching behavior](https://techdocs.akamai.com/property-mgr/docs/caching-2)\n* [Vary header](https://techdocs.akamai.com/property-mgr/docs/rm-vary-header#how-it-works)\n* [Cache Prefresh/Refresh](https://techdocs.akamai.com/property-mgr/docs/cache-prefresh-refresh)\n\n"
   }
  },
  {
   "title": "Breadcrumb test showing location object was retrieved from",
   "type": "table",
   "description": "If cacheStatus=0 it's not directly served from the Edge but might be served from Peer, Parent or Origin. We need breadcrumbs data otherwise we can't found out how served it.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "/*\n*/\nSELECT reqHost as host, reqPath as path, cacheable, count(*) as hits, SUM(rspContentLen) as totalBytes, extract(splitByString('],[', assumeNotNull(breadcrumbs))[-1],'c=(\\w)') AS location\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND rspContentType NOT IN (${content_type})\nAND statusCode = 200\nAND cacheStatus = 0\nAND notEmpty(breadcrumbs)\nGROUP BY host, path, cacheable, location\nHAVING hits > 1\nORDER BY hits DESC\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - uncachedObjects - ${__user.login}'",
     "selectedFormat": 4
    }
   ]
  }
 ]
}