{
 "title": "Akamai Client errors",
 "description": "Showing client errors but using JOIN which might be 'query' intensive.",
 "time": { "from": "2024-03-19T11:56:34.335Z", "to": "2024-03-19T12:04:14.941Z" },
 "templating": {
  "list": [
   {
    "name": "reqHost",
    "label": "Host",
    "query": "SELECT\n    replaceRegexpOne(lcase(reqHost), ':\\d*$', '')\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode IN (${errorCode:sqlstring}), $statusCode)\nGROUP BY reqHost\nORDER BY reqHost\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - 403hosts - ${__user.login}'"
   },
   {
    "name": "table",
    "query": "SELECT CONCAT((SELECT name FROM system.databases),'.', 'logs')"
   },
   {
    "name": "errorCode",
    "label": "Error Code",
    "query": "400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,421,422,423,424,425,426,428,429,431,451"
   },
   {
    "name": "database",
    "query": "SELECT name FROM system.databases"
   },
   { "name": "clientIP", "label": "ClientIP" },
   {
    "name": "AND_cliIP",
    "query": "include : IN, exclude : NOT IN\n"
   },
   { "name": "requestId", "label": "requestId" }
  ]
 },
 "panels": [
  {
   "title": "4xx resp. over time per $__interval",
   "type": "timeseries",
   "description": "Number of request group by HTTP Status Code",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT toString(statusCode) as HTTP_Status_Code, $__timeInterval(reqTimeSec) as time, count(*) as http\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode IN (${errorCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll(cliIP ${AND_cliIP} (${clientIP:sqlstring}), $clientIP)\nGROUP BY HTTP_Status_Code, time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - 4xxresp - ${__user.login}'",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "403's resp. per group CDN/WAF",
   "type": "timeseries",
   "description": "403's per attack group over time. As an INNER JOIN is taking too long, we're now combining two queries into one dashboard. So lookup the 403's in the DS data and combine that with 'deny' actions from the SIEM logs. ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "/*\n If the errorCode is not ERR_ACCESS_DENIED then only use the 'main' part before the |\n We're ignoring the ERR_ACCESS_DENIED|waf but want to know some details when delivery part is blocking the request.\n So this query will only give the requests that are blocked by the CDN for whatever reason.\n If there is no errorCode but a 403 it's blocked by the WAF.\n */\nSELECT $__timeInterval(reqTimeSec) AS time,\nIF (isNull(errorCode), 'ERR_ACCESS_DENIED_BY_ORIGIN', splitByChar('|', assumeNotNull(errorCode))[1]) AS tag, count(*) as total\nFROM ${database}.logs\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll(cliIP ${AND_cliIP} (${clientIP:sqlstring}), $clientIP)\nAND statusCode = 403\n--AND isNotNull(errorCode)\nAND (errorCode != 'ERR_ACCESS_DENIED|waf' OR isNull(errorCode))\nGROUP BY tag, time\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - 403s_logs - ${__user.login}'",
     "selectedFormat": 4
    },
    {
     "rawSql": "/*\nThis query will lookup all the deny events in the SIEM logs and will group based on the attack type, like SQLi for example\n*/\nSELECT $__timeInterval(timestamp) AS time, ruleTags[indexOf(ruleActions, 'deny')] AS tag, count(*) as total\nFROM ${database}.siem\nWHERE $__timeFilter(timestamp)\nAND hasAny(ruleActions,['deny'])\nAND $__conditionalAll( host IN (${reqHost:sqlstring}), $host)\nAND $__conditionalAll(clientIP ${AND_cliIP} (${clientIP:sqlstring}), $clientIP)\nGROUP BY tag, time\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - 403s_siem - ${__user.login}'",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "403's per rule over time using inner join. 🤞",
   "type": "table",
   "description": "Show the 403's generated by either the CDN configuration or security layer. This doesn't include and \"bot\" related mitigations like tarpit, slow etc. This will work fine for a small number of records but will timeout if there are too many records.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "/*\nNot every 403 is generated by the WAF, can be generated by the delivery config or origin which don't trigger a SIEM event.\nSo using LEFT JOIN to also get 403's without a SIEM entry but we need to create some 'dummy' CDN/Origin warnings.\nBut if blocked by the origin there is no errorCode.\n*/\nSELECT ID as requestId, time, cliIP as Client, replaceRegexpOne(lcase(reqHost), ':\\d*$', '') as reqHost, reqPath,\nif(isNull(errorCode), 'Origin', splitByChar('|', assumeNotNull(errorCode))[2]) as denied_by,\n/*\nIf there is no SIEM entry, tag and message will be null. If there is no SIEM entry it's created by the delivery config.\nBut SIEM integration might not be available yet, so creating some special if statements to check that.\nFormat of if: if(cond, then, else)\n*/\nif(denied_by = 'Origin', 'ORIGIN', if(isNull(tag), if(denied_by!='waf', 'CDN','no SIEM entry available'), tag)) AS rules,\nif(denied_by = 'Origin', 'Blocked by Origin', if(isNull(message),if(denied_by!='waf', 'Blocked by delivery configuration','no SIEM entry available'), message)) AS messages\nFROM (\n\tSELECT reqId as ID, errorCode, cliIP, replaceRegexpOne(lcase(reqHost), ':\\d*$', '') as reqHost, reqPath, reqTimeSec as time\n\tFROM ${database}.logs\n\tWHERE $__timeFilter(reqTimeSec)\n\tAND statusCode = 403\n\tAND $__conditionalAll(reqHost IN (${reqHost:sqlstring}), $reqHost)\n\tAND $__conditionalAll(cliIP ${AND_cliIP} (${clientIP:sqlstring}), $clientIP)\n\t/*\n\tif you're not interested in origin genereted 403's uncomment the isNotNull.\n\t--AND isNotNull(errorCode) \n\t*/\n\t--LIMIT 500\n) l LEFT JOIN (\n\t/* \n\tWe're only interested in the deny messages, no need to show any \"monitoring/alert\" events.\n\tLet's get the index of the first deny action and corresponding ruleMessage and ruleTag using the same index.\n\tMake sure to use the __timefilter otherwise you will see timeouts!\n\t*/\n\tSELECT requestId AS ID, indexOf(ruleActions, 'deny') AS index, ruleMessages[index] AS message, ruleTags[index] AS tag\n\tFROM ${database}.siem\n\tWHERE $__timeFilter(timestamp)\n\tAND $__conditionalAll( host IN (${reqHost:sqlstring}), $host)\n\tAND $__conditionalAll(clientIP ${AND_cliIP} (${clientIP:sqlstring}), $clientIP)\n\t-- For now only filtering on deny, this might be extended with some specific bot rules later.\n\tAND hasAny(ruleActions,['deny'])\n\t--LIMIT 500\n) r USING (ID)\nORDER BY time DESC\nLIMIT 500\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - error - ${__user.login}'\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "403's resp. per group CDN/WAF using a Grafana OUTER JOIN transformer on reqid.",
   "type": "table",
   "description": "403's per attack group over time. As an INNER JOIN is taking too long, we're now combining two queries into one dashboard. So lookup the 403's in the DS data and combine that with 'deny' actions from the SIEM logs JOINed by the requested and we're using a LIMIT.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "/*\n If the errorCode is not ERR_ACCESS_DENIED then only use the 'main' part before the |\n We're ignoring the ERR_ACCESS_DENIED|waf but want to know some details when delivery part is blocking the request.\n So this query will only give the requests that are blocked by the CDN for whatever reason.\n If there is no errorCode but a 403 it's blocked by the WAF.\n */\nSELECT reqTimeSec AS time, reqId, cliIP, reqHost, reqPath,\nIF (isNull(errorCode), 'Origin', splitByChar('|', assumeNotNull(errorCode))[2]) AS tag\nFROM ${database}.logs\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll(cliIP ${AND_cliIP} (${clientIP:sqlstring}), $clientIP)\nAND statusCode = 403\n--AND isNotNull(errorCode)\n--AND (errorCode != 'ERR_ACCESS_DENIED|waf' OR isNull(errorCode))\nORDER BY time DESC\nLIMIT 500\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - 403s_logs - ${__user.login}'",
     "selectedFormat": 1
    },
    {
     "rawSql": "/*\nThis query will lookup all the deny events in the SIEM logs and will group based on the attack type, like SQLi for example\n*/\nSELECT indexOf(ruleActions, 'deny') AS index, ruleTags[index] AS tag, requestId AS reqId, ruleMessages[index] AS message\nFROM ${database}.siem\nWHERE $__timeFilter(timestamp)\nAND hasAny(ruleActions,['deny'])\nAND $__conditionalAll( host IN (${reqHost:sqlstring}), $host)\nAND $__conditionalAll(clientIP ${AND_cliIP} (${clientIP:sqlstring}), $clientIP)\nORDER BY timestamp DESC\nLIMIT 500\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - 403s_siem - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "HTTP 4xx response codes per host",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n    count(), replaceRegexpOne(lcase(reqHost), ':\\d*$', '') as reqHost\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode IN (${errorCode:sqlstring}), $statusCode)\nAND $__conditionalAll(cliIP ${AND_cliIP} (${clientIP:sqlstring}), $clientIP)\nAND $__conditionalAll(reqHost IN (${reqHost:sqlstring}), $reqHost)\nGROUP BY reqHost\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - topPath - ${__user.login}'",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "HTTP 4xx response codes per clientIP",
   "type": "table",
   "description": "Top 10 clientIP's generating most 4xx responses",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n    count(),\n    cliIP\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode IN (${errorCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nGROUP BY cliIP\nORDER BY count() DESC\nLIMIT 10\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - error_per_client - ${__user.login}'",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "HTTP 4xx response codes per clientIP",
   "type": "table",
   "description": "Top 10 clientIP's generating most 4xx responses",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n    count(),\n    country\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode IN (${errorCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nGROUP BY country\nORDER BY count() DESC\nLIMIT 10\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - error_per_client - ${__user.login}'",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "description": "Cache Hit Ratio :\nsum of all request with cacheStatus: 1 / divided by total count of request",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n        time, cache_hit \n    FROM\n        ( SELECT\n            $__timeInterval(reqTimeSec) as time,\n            sumIf(cacheStatus, 1) as \"cached\",\n            cached/count() * 100 as \"cache_hit\" \n        FROM\n            ${table} \n        WHERE\n            $__timeFilter(reqTimeSec) \n            AND $__conditionalAll( statusCode IN (${errorCode:sqlstring}), $statusCode)\n            AND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\n            AND $__conditionalAll(cliIP ${AND_cliIP} (${clientIP:sqlstring}), $clientIP)\n        GROUP BY time \n        ORDER BY time) \n        SETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - cachehit - ${__user.login}'",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Bytes Delivered",
   "type": "timeseries",
   "description": "Sum of Total Bytes Delivered",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(reqTimeSec) as time,\nsum(totalBytes) as Bytes_Delivered\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode IN (${errorCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll(cliIP ${AND_cliIP} (${clientIP:sqlstring}), $clientIP)\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - bytes - ${__user.login}'",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Top 50 404's per reqpath",
   "type": "table",
   "description": "Check the objects that are still being requested but don't exist anymore. Maybe inform the backend team to do some cleanup. ;-)",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "WITH (\n        SELECT topK(50)(reqPath)\n        FROM ${table}\n        WHERE $__timeFilter(reqTimeSec)\n        AND statusCode = '404'\n        AND $__conditionalAll( replaceRegexpOne(lcase(reqHost), ':\\d*$', '') as reqHost IN (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${clientIP:sqlstring}), $clientIP)\n    ) AS top_50_reqPath\nSELECT\n    count(),\n    reqPath,\n    replaceRegexpOne(lcase(reqHost), ':\\d*$', '') as reqHost,\n    sum(bytes) as total_bytes,\n    round(avg(bytes)) as avg_bytes\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec) AND has(top_50_reqPath, reqPath)\nGROUP BY reqPath, reqHost\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - topPath - ${__user.login}'",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "HTTP 404 response codes per clientIP",
   "type": "table",
   "description": "Top 10 clientIP's generating most 4xx responses",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\n    count(),\n    cliIP\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND statusCode = '404'\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nGROUP BY cliIP\nORDER BY count() DESC\nLIMIT 10\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - error_per_client - ${__user.login}'",
     "selectedFormat": 4
    }
   ]
  },
  { "title": "Raw Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Edge access logs",
   "type": "logs",
   "description": "DataStream Edge Access logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "/*\nsome issues with OSS version of grafana so converting Map(String, Nullable(String)) to strings\n*/\nSELECT reqId::String,\n    toString(unknown) as unknown, \n\t\t*\n\t\tEXCEPT unknown\nFROM ${database}.logs\nWHERE $__timeFilter(reqTimeSec)\n--AND requestId = '67d24c3e'\nAND $__conditionalAll(reqId IN (${requestId:sqlstring}), $requestId)\nLIMIT 100",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "SIEM entries",
   "type": "logs",
   "description": "Raw data for the different SIEM entries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "rawSql": "/*\nsome issues with OSS version of grafana so converting Map(String, Nullable(String)) to strings\n*/\nSELECT requestId::String,\n    toString(botData) as botData,\n\t\ttoString(clientData) as clientData,\n\t\ttoString(requestHeaders) as requestHeaders,\n\t\ttoString(responseHeaders) as responseHeaders,\n\t\ttoString(userRiskData) as userRiskData, \n\t\t*\n\t\tEXCEPT (botData, clientData, requestHeaders, responseHeaders, userRiskData)\nFROM ${database}.siem\nWHERE $__timeFilter(timestamp)\n--AND requestId = '67d24c3e'\nAND $__conditionalAll(requestId IN (${requestId:sqlstring}), $requestId)\nLIMIT 100",
     "selectedFormat": 4
    }
   ]
  }
 ]
}