{
 "title": "Akamai Redirects",
 "time": { "from": "now-1h", "to": "now-1m" },
 "templating": {
  "list": [
   {
    "name": "reqHost",
    "label": "Host",
    "query": "SELECT\n    reqHost\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode IN (${redirectCode:sqlstring}), $statusCode)\nGROUP BY reqHost\nORDER BY reqHost\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - topPath - ${__user.login}'"
   },
   {
    "name": "table",
    "query": "SELECT CONCAT((SELECT name FROM system.databases),'.', 'logs')"
   },
   { "name": "redirectCode", "label": "Redirect", "query": "301,302,303,307,308" }
  ]
 },
 "panels": [
  {
   "title": "HTTP 30x response codes over time",
   "type": "timeseries",
   "description": "Number of request group by HTTP Status Code",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT toString(statusCode) as HTTP_Status_Code, $__timeInterval(reqTimeSec) as time, count(*) as http\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode IN (${redirectCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nGROUP BY HTTP_Status_Code, time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - redirects - ${__user.login}'",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Top 100 Path",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "WITH (\n        SELECT topK(100)(reqPath)\n        FROM ${table}\n        WHERE $__timeFilter(reqTimeSec)\n        AND $__conditionalAll( statusCode IN (${redirectCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\n    ) AS top_50_reqPath\nSELECT\n    count(),\n    reqPath\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec) AND has(top_50_reqPath, reqPath)\nAND $__conditionalAll( statusCode IN (${redirectCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nGROUP BY reqPath\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - top100Path - ${__user.login}'",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "HTTP 30x response codes per host",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n    count(),\n    reqHost\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode IN (${redirectCode:sqlstring}), $statusCode)\nGROUP BY reqHost\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - topHosts - ${__user.login}'",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "description": "Cache Hit Ratio :\nsum of all request with cacheStatus: 1 / divided by total count of request",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n        time, cache_hit \n    FROM\n        ( SELECT\n            $__timeInterval(reqTimeSec) as time,\n            sumIf(cacheStatus, 1) as \"cached\",\n            cached/count() * 100 as \"cache_hit\" \n        FROM\n            ${table} \n        WHERE\n            $__timeFilter(reqTimeSec) \n            AND $__conditionalAll( statusCode IN (${redirectCode:sqlstring}), $statusCode)\n            AND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\n        GROUP BY time \n        ORDER BY time) \n        SETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - cachehit - ${__user.login}'",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Bytes Delivered",
   "type": "timeseries",
   "description": "Sum of Total Bytes Delivered",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(reqTimeSec) as time,\nsum(totalBytes) as Bytes_Delivered\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode IN (${redirectCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - bytes - ${__user.login}'",
     "selectedFormat": 4
    }
   ]
  }
 ]
}