{
 "title": "Akamai Content Type",
 "time": { "from": "now-7d", "to": "now-1m" },
 "templating": {
  "list": [
   {
    "name": "reqHost",
    "label": "Host",
    "query": "SELECT\nreplaceRegexpOne(lcase(reqHost), ':\\d*$', '')\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND statusCode = 404\nGROUP BY reqHost\nORDER BY reqHost\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - 403hosts - ${__user.login}'"
   },
   {
    "name": "table",
    "query": "SELECT CONCAT((SELECT name FROM system.databases),'.', 'logs')"
   },
   {
    "name": "database",
    "query": "SELECT name FROM system.databases"
   },
   { "name": "content", "label": "content", "query": "image" }
  ]
 },
 "panels": [
  {
   "title": "Response Content Length per host",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/*\nSometimes you will see :443 in the reqHost, just clean that up using replace.\nUsing replaceRegexpOne in stead of REPLACE this time.\n*/\nSELECT reqHost as host, sum(rspContentLen) as contentLength\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nGROUP BY host\nORDER BY contentLength DESC\nLIMIT 10\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - 404resp - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Response Content Length per content Type",
   "type": "bargauge",
   "description": "We combined the different image formats like image/jpg image/webp into one group",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/*\nSometimes you will see :443 in the reqHost, just clean that up using replace.\nUsing replaceRegexpOne in stead of REPLACE this time.\n*/\nSELECT if(splitByChar('/',assumeNotNull(rspContentType))[1] = 'image', 'image', rspContentType) as contentType, sum(rspContentLen) as contentLength\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND rspContentType IS NOT NULL\nGROUP BY contentType\nORDER BY contentLength DESC\nLIMIT 10\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - 404resp - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Image bytes delivered over time per $__interval",
   "type": "timeseries",
   "description": "Get the bytes per image type over time. Using CUBE to automatically calculated the total per interval.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "\nSELECT  $__timeInterval(reqTimeSec) as time, splitByChar('/',assumeNotNull(rspContentType))[2] as contentType, sum(rspContentLen) as bytes\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND rspContentType LIKE 'image/%'\nGROUP BY time, contentType WITH CUBE\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - image - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Bytes per specific image content-type",
   "type": "bargauge",
   "description": "Filtering all request for objects where a 404 is returned and grouping them based on extension. If there is no extension using /",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/*\n\n*/\nSELECT splitByChar('/',assumeNotNull(rspContentType))[2] as contentType, sum(rspContentLen) as contentLength\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND rspContentType IS NOT NULL\nAND rspContentType LIKE 'image/%'\nGROUP BY contentType\nORDER BY contentLength DESC\nLIMIT 10\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - 404resp - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Response Content Length per content Type",
   "type": "piechart",
   "description": "We combined the different image formats like image/jpg image/webp into one group",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/*\nSometimes you will see :443 in the reqHost, just clean that up using replace.\nUsing replaceRegexpOne in stead of REPLACE this time.\n*/\nSELECT IF(splitByChar('/',assumeNotNull(rspContentType))[1] = 'image', 'image', rspContentType) as contentType, sum(rspContentLen) as contentLength\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND rspContentType IS NOT NULL\nGROUP BY contentType\nORDER BY contentLength DESC\nLIMIT 10\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - 404resp - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Bytes per specific image content-type $content",
   "type": "table",
   "description": "Filtering all request for objects where a 404 is returned and grouping them based on extension. If there is no extension using /",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "/*\n\n*/\nSELECT sum(rspContentLen) as total, reqHost, reqPath, count(*) as hits\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND rspContentType LIKE '$content%'\nGROUP BY reqHost, reqPath\nORDER BY total DESC\nLIMIT 50\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - 404resp - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  }
 ]
}