{
 "title": "Akamai Not Found",
 "time": { "from": "now-2d", "to": "now-1m" },
 "templating": {
  "list": [
   {
    "name": "reqHost",
    "label": "Host",
    "query": "SELECT\n    reqHost\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND statusCode = 404\nGROUP BY reqHost\nORDER BY reqHost\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - 403hosts - ${__user.login}'"
   },
   {
    "name": "table",
    "query": "SELECT CONCAT((SELECT name FROM system.databases),'.', 'logs')"
   },
   {
    "name": "database",
    "query": "SELECT name FROM system.databases"
   },
   {
    "name": "AND_cliIP",
    "query": "include : IN, exclude : NOT IN\n"
   }
  ]
 },
 "panels": [
  {
   "title": "404 resp. over time per $__interval",
   "type": "timeseries",
   "description": "Number of calls to objects not found (404)",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(reqTimeSec) as time, count(*) as hits, reqHost as host\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND statusCode = 404\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nGROUP BY time, host\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - 404resp - ${__user.login}'",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "404's resp. per extension",
   "type": "barchart",
   "description": "Filtering all request for objects where a 404 is returned and grouping them based on extension. If there is no extension using /",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT if(like(splitByChar('.', assumeNotNull(reqPath))[-1] AS ext, '%/%'), '/', ext) AS extension, count() as hits, sum(totalBytes) as Bytes_Delivered\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND reqPath IS NOT NULL\nAND statusCode = 404\nGROUP BY extension\nORDER BY hits DESC\nLIMIT 5\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - top-404-ext - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "404's bytes delivered per extension",
   "type": "barchart",
   "description": "Filtering all request for objects where a 404 is returned and grouping them based on extension. If there is no extension using /",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Top 50 404's per reqpath",
   "type": "table",
   "description": "Check the objects that are still being requested but don't exist anymore. Maybe inform the backend team to do some cleanup. ;-)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "WITH (\n        SELECT topK(50)(reqPath)\n        FROM ${table}\n        WHERE $__timeFilter(reqTimeSec)\n        AND statusCode = '404'\n        AND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\n    ) AS top_50_reqPath\nSELECT\n    count() as hits,\n    reqPath,\n    reqHost,\n    sum(bytes) as total_bytes,\n    round(avg(bytes)) as avg_bytes\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec) AND has(top_50_reqPath, reqPath)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nGROUP BY reqPath, reqHost\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - topPath - ${__user.login}'",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Bytes Delivered",
   "type": "timeseries",
   "description": "Sum of Total Bytes Delivered",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(reqTimeSec) as time,\nsum(totalBytes) as Bytes_Delivered\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND statusCode = 404\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - bytes - ${__user.login}'",
     "selectedFormat": 4
    }
   ]
  }
 ]
}