{
 "title": "HTTP Response groups",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "table",
    "query": "SELECT CONCAT((SELECT name FROM system.databases),'.', 'logs')"
   },
   {
    "name": "reqHost",
    "label": "reqHost",
    "query": "SELECT\n    reqHost\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nGROUP BY reqHost\nORDER BY reqHost\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - hosts - ${__user.login}'"
   }
  ]
 },
 "panels": [
  {
   "title": "Redirection messages (300's)",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "-- convert statusCode results to string otherwise we have two counters.\nSELECT toString(statusCode) as http_group, count(*) as total\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND statusCode BETWEEN 299 AND 399\nGROUP BY http_group\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - httpcodes - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "HTTP Status code groups over time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "-- convert statusCode results to string otherwise we have two counters.\nSELECT toString(round(statusCode, -2)) as http_group, $__timeInterval(reqTimeSec) as time, count(*) as total\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nGROUP BY http_group, time \nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - httpcodes - ${__user.login}'"
    }
   ]
  },
  {
   "title": "Client error messages (400's)",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "-- convert statusCode results to string otherwise we have two counters.\nSELECT toString(statusCode) as http_group, count(*) as total\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND statusCode BETWEEN 399 AND 499\nGROUP BY http_group\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - httpcodes_client_error - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Akamai status news feed",
   "type": "news",
   "gridPos": { "h": 21, "w": 18, "x": 6, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server Error  messages (500's)",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "-- convert statusCode results to string otherwise we have two counters.\nSELECT toString(statusCode) as http_group, count(*) as total\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND statusCode BETWEEN 499 AND 599\nGROUP BY http_group\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - server_errors - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  }
 ]
}