{
 "title": "Akamai Unknown Bots",
 "description": "Information about Akamai known bots ",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "table",
    "query": "SELECT CONCAT((SELECT name FROM system.databases),'.', 'siem')"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "SELECT host\nFROM ${table}\nWHERE $__timeFilter(timestamp)\nAND has(ruleTags, 'AKAMAI/BOT/USER_BEHAVIOR')\nGROUP BY host\nORDER BY host\nLIMIT 100"
   },
   { "name": "limit", "label": "Limit", "query": "1,2,3,4,5,6,7,8,9,10" }
  ]
 },
 "panels": [
  {
   "title": "All Akamai detected behavioural (BMP) endpoint req. over Time per host",
   "type": "timeseries",
   "description": "Akamai Unknown Bots req. over time per host with the top ${limit} hosts.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT host, count() as hits, $__timeInterval(timestamp) as time, path\nFROM ${table}\n  WHERE $__timeFilter(timestamp)\n  /*\n  BMP protected endpoints will have a entry in the ruleTags array of AKAMAI/BOT/USER_BEHAVIOR\n  The botData field is a map for string with [score|response]\n  Looks like the response has the following \n  0|4 = Safeguard (we don't know the exact code for safeguard yet)\n  1 = Cautious Response\n  2 = Strict Response\n  3 = Aggressive Response\n  \n  so 100:3 in botData field is a score of 100 with Aggressive Response assigned to it.\n  */\n  AND has(ruleTags, 'AKAMAI/BOT/USER_BEHAVIOR')\n  AND $__conditionalAll(host IN (${host:sqlstring}), $host)\n  GROUP BY time, host, path\n  ORDER BY time, hits DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - wrong_behavior_bots - ${__user.login}'"
    }
   ]
  },
  {
   "title": "Akamai Behavioural Detected Bots (BMP)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "/*\nBMP protected endpoints will have a entry in the ruleTags array of AKAMAI/BOT/USER_BEHAVIOR\n\nThe botData field is a map  with {\"botScore\":\"100\",\"responseSegment\":\"3\"}\nLooks like the responseSegement has the following mapping:\n  1 = Cautious Response\n  2 = Strict Response\n  3 = Aggressive Response\n  4 = Safeguard Response\n\nGrafana can't deal very well with map fiels so converting it to string\n*/\nSELECT host, path, toInt8(botData['responseSegment']) as responseSegment , count()\nFROM ${table}\n  WHERE $__timeFilter(timestamp)\n  \n  AND has(ruleTags, 'AKAMAI/BOT/USER_BEHAVIOR')\n  AND $__conditionalAll(host IN (${host:sqlstring}), $host)\n  GROUP BY host, path, responseSegment\n  ORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - wrong_behavior_bots - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Hits per Response Groups",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Top 10 clientIP's detected by BMP per host/path",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT host, path, clientIP, count() as hits\nFROM ${table}\n  WHERE $__timeFilter(timestamp)\n\n  AND has(ruleTags, 'AKAMAI/BOT/USER_BEHAVIOR')\n  AND $__conditionalAll(host IN (${host:sqlstring}), $host)\n  GROUP BY host, path, clientIP\n  ORDER BY hits DESC\n  LIMIT 10\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - wrong_behavior_bots - ${__user.login}'",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Request per client detected by BMP",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "panelId": 21 }
   ]
  },
  {
   "title": "BMP hits per country",
   "type": "geomap",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT country, count() as hits\nFROM ${table}\n  WHERE $__timeFilter(timestamp)\n  AND has(ruleTags, 'AKAMAI/BOT/USER_BEHAVIOR')\n  AND $__conditionalAll(host IN (${host:sqlstring}), $host)\n  GROUP BY country\n  ORDER BY hits DESC\n  LIMIT 10\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - wrong_behavior_bots - ${__user.login}'",
     "selectedFormat": 4
    }
   ]
  }
 ]
}