{
 "title": "Akamai Compressed Objects Traffic & Uncompressed Objects Traffic",
 "time": { "from": "now-1h", "to": "now-1m" },
 "templating": {
  "list": [
   { "name": "AND_statusCode", "query": "include : IN, exclude : NOT IN" },
   {
    "name": "statusCode",
    "label": "HTTP Status Code",
    "query": "200,201,202,204,205,206,301,302,304,307,308,400,401,403,404,405,406,408,409,410,411,412,413,414,415,416,417,421,425,428,429,431,451,500,501,502,503,504,505,506,511"
   },
   { "name": "AND_cacheStatus", "query": "include : IN, exclude : NOT IN" },
   { "name": "cacheStatus", "label": "Cache Status", "query": "true : 1, false : 0" },
   { "name": "AND_reqHost", "query": "include : IN, exclude : NOT IN" },
   {
    "name": "reqHost",
    "label": "Hostname",
    "query": "SELECT arrayJoin(topK(50)(reqHost)) FROM ${table} WHERE $__timeFilter(reqTimeSec)"
   },
   { "name": "AND_reqMethod", "query": "include : IN, exclude : NOT IN" },
   {
    "name": "reqMethod",
    "label": "Method",
    "query": "SELECT arrayJoin(topK(50)(reqMethod)) FROM ${table} WHERE $__timeFilter(reqTimeSec)"
   },
   { "name": "AND_UA", "query": "include : IN, exclude : NOT IN" },
   { "name": "UA", "label": "User Agent" },
   { "name": "AND_rspContentType", "query": "include : IN, exclude : NOT IN" },
   {
    "name": "rspContentType",
    "label": "Content Type",
    "query": "SELECT arrayJoin(topK(50)(rspContentType)) FROM ${table} WHERE $__timeFilter(reqTimeSec)"
   },
   { "name": "AND_errorCode", "query": "include : IN, exclude : NOT IN" },
   {
    "name": "errorCode",
    "label": "Error Code",
    "query": "SELECT arrayJoin(topK(50)(errorCode)) FROM ${table} WHERE $__timeFilter(reqTimeSec)"
   },
   { "name": "edge_response_time_percentile", "label": "Edge Response Time Percentile", "query": "0.5 , 0.75 , 0.90 , 0.95, 0.99" },
   { "name": "AND_reqPath", "query": "include : IN, exclude : NOT IN" },
   { "name": "reqPath", "label": "Path" },
   { "name": "AND_cliIP", "query": "include : IN, exclude : NOT IN" },
   { "name": "cliIP", "label": "Client IP" },
   { "name": "AND_country", "query": "include : IN, exclude : NOT IN" },
   {
    "name": "country",
    "label": "Country",
    "query": "SELECT arrayJoin(topK(50)(country)) FROM ${table} WHERE $__timeFilter(reqTimeSec)"
   },
   { "name": "AND_cp", "query": "include : IN, exclude : NOT IN" },
   {
    "name": "cp",
    "label": "CPCode",
    "query": "SELECT arrayJoin(topK(50)(cp)) FROM ${table} WHERE $__timeFilter(reqTimeSec)"
   },
   {
    "name": "transferTimeMSec_percentile",
    "query": "$__conditionalAll(SELECT quantile(${edge_response_time_percentile})(transferTimeMSec) FROM ${table} WHERE $__timeFilter(reqTimeSec),$edge_response_time_percentile)"
   },
   {
    "name": "metric_name",
    "label": "Filter on Metric",
    "query": "SELECT name\nFROM system.columns\nWHERE database = splitByChar('.', '${table}')[1]\nAND table = splitByChar('.', '${table}')[2]\nAND type IN ('Nullable(UInt8)', 'Nullable(UInt16)', 'Nullable(UInt32)', 'Nullable(UInt64)', 'Nullable(Int8)', 'Nullable(Int16)', 'Nullable(Int32)', 'Nullable(Int64)', 'UInt8', 'UInt16', 'UInt32', 'UInt64', 'Int8', 'Int16', 'Int32', 'Int64', 'Float', 'Nullable(Float)')"
   },
   { "name": "metric_filter", "query": "<,>, <=, >=,=" },
   { "name": "metric_value" },
   {
    "name": "table",
    "query": "SELECT CONCAT((SELECT name FROM system.databases),'.', 'logs')"
   },
   {
    "name": "catalog",
    "query": "SELECT concat(project,'.`',table,'#.catalog`')\nFROM (SELECT splitByChar('.','${table}')[1] as project, splitByChar('.','${table}')[2] as table)"
   },
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Request Per Content Type Without Compression",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\ncount(),\nrspContentType\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND rspContentType IS not NULL\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\nAND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\nAND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(UA ${AND_UA} (${UA:sqlstring}), $UA)\nAND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nAND $__conditionalAll(cp ${AND_cp} (${cp:sqlstring}), $cp)\nAND ( uncompressedSize IS  NULL )\nGROUP BY rspContentType ORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - content_type - ${__user.login}'"
    }
   ]
  },
  {
   "title": "Request Per Content Type Compreseed Files",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\ncount(),\nrspContentType\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND rspContentType IS not NULL\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\nAND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\nAND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(UA ${AND_UA} (${UA:sqlstring}), $UA)\nAND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nAND $__conditionalAll(cp ${AND_cp} (${cp:sqlstring}), $cp)\nAND ( uncompressedSize IS NOT NULL )\nGROUP BY rspContentType ORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - content_type - ${__user.login}'"
    }
   ]
  },
  {
   "title": "Total Traffic of Uncompressed Files",
   "type": "gauge",
   "description": "Diferencia entre total bytes y el obj comprimido",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(reqTimeSec) as time,\nsum(totalBytes) as Total_Bytes,\nsum((bytes)) as Total_Content_Bytes_Served_in_Response_Body\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\nAND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\nAND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(UA ${AND_UA} (${UA:sqlstring}), $UA)\nAND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nAND $__conditionalAll(cp ${AND_cp} (${cp:sqlstring}), $cp)\nAND ( uncompressedSize IS  NULL )\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - bytes - ${__user.login}'"
    }
   ]
  },
  {
   "title": "Total Traffic of Compressed Files",
   "type": "gauge",
   "description": "Diferencia entre total bytes y el obj comprimido",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(reqTimeSec) as time,\nsum(totalBytes) as Total_Bytes,\nsum((bytes)) as Total_Content_Bytes_Served_in_Response_Body,\nsum(totalBytes- (bytes )) as Difference_in_Bytes\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\nAND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\nAND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(UA ${AND_UA} (${UA:sqlstring}), $UA)\nAND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nAND $__conditionalAll(cp ${AND_cp} (${cp:sqlstring}), $cp)\nAND ( uncompressedSize IS NOT NULL )\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - bytes - ${__user.login}'"
    }
   ]
  },
  {
   "title": "Traffic Without Compression",
   "type": "piechart",
   "description": "Diference between the reported billed traffic and Content length delivered",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(reqTimeSec) as time,\nsum(totalBytes) as Total_bytes,\nsum((bytes)) as Total_Content_Bytes_Server_in_Response_Body,\nsum(totalBytes- (bytes)) as Difference_in_bytes\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\nAND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\nAND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(UA ${AND_UA} (${UA:sqlstring}), $UA)\nAND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nAND $__conditionalAll(cp ${AND_cp} (${cp:sqlstring}), $cp)\nAND ( uncompressedSize IS  NULL )\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - bytes - ${__user.login}'"
    }
   ]
  },
  {
   "title": "Compressed Files Traffic",
   "type": "piechart",
   "description": "Diference between the reported billed traffic and traffic delivered",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(reqTimeSec) as time,\nsum(totalBytes) as Total_bytes,\nsum((bytes)) as Total_Content_Bytes_Server_in_Response_Body,\nsum(totalBytes- (bytes )) as Difference_in_bytes\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\nAND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\nAND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(UA ${AND_UA} (${UA:sqlstring}), $UA)\nAND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nAND $__conditionalAll(cp ${AND_cp} (${cp:sqlstring}), $cp)\nAND ( uncompressedSize IS NOT NULL )\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - bytes - ${__user.login}'"
    }
   ]
  },
  {
   "title": "Traffic Without Compressed Files",
   "type": "timeseries",
   "description": "Diferencia entre total bytes y el obj comprimido",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(reqTimeSec) as time,\nsum(totalBytes) as Total_Bytes,\nsum((bytes)) as Total_Content_Bytes_Served_in_Response_Body\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\nAND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\nAND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(UA ${AND_UA} (${UA:sqlstring}), $UA)\nAND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nAND $__conditionalAll(cp ${AND_cp} (${cp:sqlstring}), $cp)\nAND( uncompressedSize IS  NULL )\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - bytes - ${__user.login}'"
    }
   ]
  },
  {
   "title": "Compressed Files Traffic",
   "type": "timeseries",
   "description": "Diferencia entre total bytes y el obj comprimido",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(reqTimeSec) as time,\nsum(totalBytes) as Total_Bytes,\nsum((bytes)) as Total_Content_Bytes_Served_in_Response_Body\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\nAND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\nAND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(UA ${AND_UA} (${UA:sqlstring}), $UA)\nAND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nAND $__conditionalAll(cp ${AND_cp} (${cp:sqlstring}), $cp)\nAND( uncompressedSize IS NOT NULL )\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - bytes - ${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 50 Path (not Compressed Files)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "WITH (\n        SELECT topK(50)(reqPath)\n        FROM ${table}\n        WHERE $__timeFilter(reqTimeSec)\n        AND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\n        AND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\n        AND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\n        AND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\n        AND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\n        AND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\n        AND $__conditionalAll(UA ${AND_UA} (${UA:sqlstring}), $UA)\n        AND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\n        AND $__conditionalAll(cp ${AND_cp} (${cp:sqlstring}), $cp)\n        AND ( uncompressedSize IS NULL )\n    ) AS top_50_reqPath\nSELECT\n    count(),\n    reqPath\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec) AND has(top_50_reqPath, reqPath)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\n        AND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\n        AND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\n        AND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\n        AND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\n        AND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\n        AND $__conditionalAll(UA ${AND_UA} (${UA:sqlstring}), $UA)\n        AND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\n        AND $__conditionalAll(cp ${AND_cp} (${cp:sqlstring}), $cp)\nGROUP BY reqPath\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - topPath - ${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 50 Path (Compressed Files)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "WITH (\n        SELECT topK(50)(reqPath)\n        FROM ${table}\n        WHERE $__timeFilter(reqTimeSec)\n        AND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\n        AND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\n        AND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\n        AND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\n        AND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\n        AND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\n        AND $__conditionalAll(UA ${AND_UA} (${UA:sqlstring}), $UA)\n        AND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\n        AND $__conditionalAll(cp ${AND_cp} (${cp:sqlstring}), $cp)\n        AND ( uncompressedSize IS NOT NULL )\n    ) AS top_50_reqPath\nSELECT\n    count(),\n    reqPath\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec) AND has(top_50_reqPath, reqPath)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\n        AND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\n        AND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\n        AND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\n        AND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\n        AND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\n        AND $__conditionalAll(UA ${AND_UA} (${UA:sqlstring}), $UA)\n        AND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\n        AND $__conditionalAll(cp ${AND_cp} (${cp:sqlstring}), $cp)\n        AND ( uncompressedSize IS NOT NULL )\nGROUP BY reqPath\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - topPath - ${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 50 User Agent",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "WITH (\n        SELECT topK(50)(UA)\n        FROM ${table}\n        WHERE $__timeFilter(reqTimeSec)\n        AND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\n        AND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\n        AND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\n        AND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\n        AND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\n        AND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\n        AND $__conditionalAll(UA ${AND_UA} (${UA:sqlstring}), $UA)\n        AND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\n        AND $__conditionalAll(cp ${AND_cp} (${cp:sqlstring}), $cp)\n        AND ( uncompressedSize IS  NULL )\n    ) AS top_50_UA\nSELECT\n    count(),\n    UA\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec) AND has(top_50_UA, UA)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\n        AND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\n        AND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\n        AND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\n        AND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\n        AND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\n        AND $__conditionalAll(UA ${AND_UA} (${UA:sqlstring}), $UA)\n        AND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\n        AND $__conditionalAll(cp ${AND_cp} (${cp:sqlstring}), $cp)\n        AND ( uncompressedSize IS  NULL )\nGROUP BY UA\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - topUA - ${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 50 User Agent",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "rawSql": "WITH (\n        SELECT topK(50)(UA)\n        FROM ${table}\n        WHERE $__timeFilter(reqTimeSec)\n        AND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\n        AND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\n        AND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\n        AND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\n        AND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\n        AND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\n        AND $__conditionalAll(UA ${AND_UA} (${UA:sqlstring}), $UA)\n        AND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\n        AND $__conditionalAll(cp ${AND_cp} (${cp:sqlstring}), $cp)\n        AND ( uncompressedSize IS NOT NULL )\n    ) AS top_50_UA\nSELECT\n    count(),\n    UA\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec) AND has(top_50_UA, UA)\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\n        AND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\n        AND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\n        AND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\n        AND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\n        AND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\n        AND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\n        AND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\n        AND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\n        AND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\n        AND $__conditionalAll(UA ${AND_UA} (${UA:sqlstring}), $UA)\n        AND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\n        AND $__conditionalAll(cp ${AND_cp} (${cp:sqlstring}), $cp)\n        AND ( uncompressedSize IS  NOT NULL )\nGROUP BY UA\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - topUA - ${__user.login}'"
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raw Logs",
     "type": "logs",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "rawSql": "WITH (\n    WITH 1000 AS LATEST\n    SELECT [min($__fromTime), max($__toTime)] AS min_max\n    FROM (\n        SELECT\n            *,\n            any(running_row_count) OVER (ORDER BY min_timestamp DESC ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) AS prev_running_row_count,\n            (running_row_count > LATEST) AND (prev_running_row_count < LATEST) AS is_boundary_row\n        FROM (\n            SELECT\n                min_timestamp,\n                max_timestamp,\n                sum(rows) OVER (ORDER BY min_timestamp DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_row_count\n            FROM ${catalog}\n            ORDER BY max_timestamp DESC, min_timestamp ASC\n        )\n        ORDER BY max_timestamp DESC, min_timestamp ASC\n    )\n    WHERE (running_row_count < LATEST) OR is_boundary_row\n) AS min_max\n\nSELECT statusCode::String, * EXCEPT (statusCode, unknown)\nFROM ${table}\nWHERE reqTimeSec BETWEEN min_max[1] AND min_max[2]\nAND $__conditionalAll( statusCode ${AND_statusCode} (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost ${AND_reqHost} (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus ${AND_cacheStatus} (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod ${AND_reqMethod} (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType ${AND_rspContentType} (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode ${AND_errorCode} (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll( transferTimeMSec >= ${transferTimeMSec_percentile}, $transferTimeMSec_percentile)\nAND $__conditionalAll(${metric_name} ${metric_filter} ${metric_value}, $metric_filter)\nAND $__conditionalAll(reqPath ${AND_reqPath} (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP ${AND_cliIP} (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(UA ${AND_UA} (${UA:sqlstring}), $UA)\nAND $__conditionalAll(country ${AND_country} (${country:sqlstring}), $country)\nAND $__conditionalAll(cp ${AND_cp} (${cp:sqlstring}), $cp)\nORDER BY reqTimeSec DESC\nLIMIT 1000\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - rawlogs - ${__user.login}'"
      }
     ]
    }
   ]
  }
 ]
}