{
 "title": "Akamai HTTP Client Errors Codes (400's)",
 "description": "some more details regarding the different client errors (400s)",
 "time": { "from": "now-6h", "to": "now-1m" },
 "templating": {
  "list": [
   {
    "name": "reqHost",
    "label": "Host",
    "query": "SELECT\nreplaceRegexpOne(lcase(reqHost), ':\\d*$', '')\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND statusCode = 404\nGROUP BY reqHost\nORDER BY reqHost\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - 403hosts - ${__user.login}'"
   },
   {
    "name": "table",
    "query": "SELECT CONCAT((SELECT name FROM system.databases),'.', 'logs')"
   },
   {
    "name": "database",
    "query": "SELECT name FROM system.databases"
   },
   { "name": "error", "label": "error", "query": "400,401,403,404" }
  ]
 },
 "panels": [
  {
   "title": "${error} resp. over time per $__interval",
   "type": "timeseries",
   "description": "Number of calls to objects with specific error",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "/*\nSometimes you will see :443 in the reqHost, just clean that up using replace.\nUsing replaceRegexpOne in stead of REPLACE this time.\n*/\nSELECT $__timeInterval(reqTimeSec) as time, count(*) as hits, replaceRegexpOne(lcase(reqHost), ':443', '') as host\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND statusCode = ${error}\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nGROUP BY time, host\nORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - ${Error} resp - ${__user.login}'"
    }
   ]
  },
  {
   "title": "${error} resp. per extension",
   "type": "barchart",
   "description": "Filtering all request for objects where a 404 is returned and grouping them based on extension. If there is no extension using /",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "/*\nSelecting objects responding with a 404 and checking the sum of the object lenght being served for these 404's.\nGrouping them based on extenion or / if no extension exists.\n*/\nSELECT if(like(splitByChar('.', assumeNotNull(reqPath))[-1] AS ext, '%/%'), '/', ext) AS extension, count() as hits, sum(rspContentLen) as Bytes_Delivered\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND reqPath IS NOT NULL\nAND statusCode = ${error}\nGROUP BY extension\nORDER BY hits DESC\nLIMIT 10\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - top-404-ext - ${__user.login}'"
    }
   ]
  },
  {
   "title": "${error} bytes delivered per extension",
   "type": "barchart",
   "description": "Filtering all request for objects where a 404 is returned and grouping them based on extension. If there is no extension using /",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "panelId": 20 }
   ]
  },
  {
   "title": "Top 50 ${error}'s per reqpath",
   "type": "table",
   "description": "Check the objects that are still being requested but don't exist anymore. Maybe inform the backend team to do some cleanup. ;-)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "WITH (\n        SELECT topK(50)(reqPath)\n        FROM ${table}\n        WHERE $__timeFilter(reqTimeSec)\n        AND statusCode = ${error}\n        AND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\n    ) AS top_50_reqPath\nSELECT\n    count() as hits,\n    reqPath,\n    reqHost,\n    sum(bytes) as total_bytes,\n    round(avg(bytes)) as avg_bytes\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec) AND has(top_50_reqPath, reqPath)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND statusCode = ${error}\nGROUP BY reqPath, reqHost\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - topPath - ${__user.login}'"
    }
   ]
  },
  {
   "title": "Top 50 ${error}'s per cliIP and path",
   "type": "table",
   "description": "Check the objects that are still being requested but don't exist anymore. Maybe inform the backend team to do some cleanup. ;-)",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "WITH (\n        SELECT topK(50)(cliIP)\n        FROM ${table}\n        WHERE $__timeFilter(reqTimeSec)\n        AND statusCode = ${error}\n        AND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\n    ) AS top_50_cliIP\nSELECT\n    count() as hits,\n    cliIP,\n    country,\n    reqPath,\n    reqHost\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec) AND has(top_50_cliIP, cliIP)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND statusCode = ${error}\nGROUP BY cliIP,country, reqPath, reqHost\nORDER BY count() DESC\nSETTINGS hdx_query_max_execution_time=120, hdx_query_admin_comment='akamai - topPath - ${__user.login}'"
    }
   ]
  },
  {
   "title": "${error} requests per country (top 5)",
   "type": "geomap",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 39 },
   "targets": [
    { "panelId": 22 }
   ]
  },
  {
   "title": "Bytes Delivered",
   "type": "timeseries",
   "description": "Sum of Total Bytes Delivered",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(reqTimeSec) as time,\nsum(totalBytes) as Bytes_Delivered\nFROM ${table}\nWHERE $__timeFilter(reqTimeSec)\nAND statusCode = ${error}\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nGROUP BY time ORDER BY time\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - bytes - ${__user.login}'"
    }
   ]
  }
 ]
}