{
 "title": "Cache Analysis Treemap",
 "time": { "from": "now-24h", "to": "now-1m" },
 "templating": {
  "list": [
   {
    "name": "reqHost",
    "label": "Hostname",
    "query": "SELECT reqHost FROM ${ds2} WHERE $__timeFilter(reqTimeSec) GROUP BY reqHost ORDER BY COUNT() DESC LIMIT 50"
   },
   { "name": "reqPath", "label": "Path" },
   {
    "name": "rspContentType",
    "label": "Content Type",
    "query": "SELECT rspContentType FROM ${ds2} WHERE $__timeFilter(reqTimeSec) GROUP BY rspContentType ORDER BY COUNT() DESC LIMIT 50"
   },
   {
    "name": "statusCode",
    "label": "HTTP Status Code",
    "query": "200,201,202,204,205,206,301,302,304,307,308,400,401,403,404,405,406,408,409,410,411,412,413,414,415,416,417,421,425,428,429,431,451,500,501,502,503,504,505,506,511"
   },
   { "name": "cacheStatus", "label": "Cache Status", "query": "true : 1, false : 0" },
   {
    "name": "reqMethod",
    "label": "Method",
    "query": "SELECT reqMethod FROM ${ds2} WHERE $__timeFilter(reqTimeSec) GROUP BY reqMethod ORDER BY COUNT() DESC LIMIT 50"
   },
   { "name": "UA", "label": "User Agent" },
   {
    "name": "errorCode",
    "label": "Error Code",
    "query": "SELECT errorCode FROM ${ds2} WHERE $__timeFilter(reqTimeSec) GROUP BY errorCode ORDER BY COUNT() DESC LIMIT 50"
   },
   { "name": "cliIP", "label": "Client IP" },
   {
    "name": "ds2",
    "query": "SELECT CONCAT((SELECT name FROM system.databases),'.', 'logs')"
   },
   {
    "name": "country",
    "label": "Country",
    "query": "select country from ${ds2}\nwhere $__timeFilter(reqTimeSec)\ngroup by country order by count(country) desc\nlimit 250"
   },
   { "name": "summary", "query": "${VAR_SUMMARY}" },
   {
    "name": "aggregation",
    "label": "Aggregation",
    "query": "average : avgIf , Median : quantileIf(0.5) , P75 : quantileIf(0.75) , P90 : quantileIf(0.90) , P95 : quantileIf(0.95)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  count(*) as count \nFROM ${ds2}\nwhere $__timeFilter(reqTimeSec) \nAND $__conditionalAll( statusCode IN (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus IN (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod IN (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType IN (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode IN (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll(reqPath IN (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP IN (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(UA IN (${UA:sqlstring}), $UA)\nAND $__conditionalAll(country IN (${country:sqlstring}), $country)\nLIMIT 100",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Offload by Hostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT  reqHost as hostname, \ncountIf(cacheStatus=1)/count(cacheStatus) as offload,\n$__timeInterval(reqTimeSec) as time\nFROM ${ds2}\nwhere $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode IN (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus IN (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod IN (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType IN (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode IN (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll(reqPath IN (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP IN (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(UA IN (${UA:sqlstring}), $UA)\nAND $__conditionalAll(country IN (${country:sqlstring}), $country)\ngroup by hostname, time\norder by time asc, hostname desc\n\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Overall Offload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT countIf(cacheStatus=1)/count(cacheStatus) as offload\nFROM ${ds2}\nwhere $__timeFilter(reqTimeSec) \nAND $__conditionalAll( statusCode IN (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus IN (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod IN (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType IN (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode IN (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll(reqPath IN (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP IN (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(UA IN (${UA:sqlstring}), $UA)\nAND $__conditionalAll(country IN (${country:sqlstring}), $country)\nLIMIT 100",
     "selectedFormat": 4
    }
   ]
  },
  { "title": "Treemaps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Offload by Hostname",
   "type": "marcusolsson-treemap-panel",
   "description": "Offload rate broken out by content-type",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT  \n  ifNull(reqHost,'-') as Hostname,\n  countIf(cacheStatus)/count(*) as offloadRate,\n  count(*) as count\nFROM ${ds2}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode IN (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus IN (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod IN (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType IN (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode IN (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll(reqPath IN (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP IN (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(UA IN (${UA:sqlstring}), $UA)\nAND $__conditionalAll(country IN (${country:sqlstring}), $country)\nGROUP BY Hostname \nORDER BY count desc\nlimit 200\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Offload by Content-Type",
   "type": "marcusolsson-treemap-panel",
   "description": "Offload rate broken out by content-type",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT  \n  ifNull(rspContentType,'-') as ContentType,\n  1.0*sumIf(cacheStatus,cacheStatus=1)/count(*) as offloadRate,\n  count(*) as count\nFROM ${ds2}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode IN (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus IN (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod IN (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType IN (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode IN (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll(reqPath IN (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP IN (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(UA IN (${UA:sqlstring}), $UA)\nAND $__conditionalAll(country IN (${country:sqlstring}), $country)\nGROUP BY rspContentType \nORDER BY count desc\nlimit 200\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Offload by Resource",
   "type": "marcusolsson-treemap-panel",
   "description": "Number of request group by HTTP Status Code",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT  \n  ifNull(concat(reqHost,reqPath),'-') as url,\n  /*  use this if the path might contain the word 'undefined': replaceOne(ifNull(concat(reqHost,reqPath),'-'),'undefined','undefine_d') as url, */\n  reqHost,\n  reqPath,\n  countIf(cacheStatus)/count(*) as offloadRate,\n  count(*) as count\nFROM ${ds2}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode IN (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus IN (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod IN (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType IN (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode IN (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll(reqPath IN (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP IN (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(UA IN (${UA:sqlstring}), $UA)\nAND $__conditionalAll(country IN (${country:sqlstring}), $country)\nGROUP BY url ,reqHost,reqPath\nORDER BY count desc\nlimit 500\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Caching Impact (${aggregation})",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT  \nconcat(reqHost,reqPath) as url,\ncount(*) as count,\ncountIf(cacheStatus)/count(*) as offload,\navg(totalBytes) as avgBytes,\n${aggregation}(turnAroundTimeMSec,cacheStatus) as cachedTurnAroundTime,\n${aggregation}(turnAroundTimeMSec, not cacheStatus) as uncachedTurnAroundTime,\n${aggregation}(transferTimeMSec,cacheStatus) as cachedTransferTimeMSec,\n${aggregation}(transferTimeMSec, not cacheStatus) as uncachedTransferTimeMSec,\n(uncachedTurnAroundTime-cachedTurnAroundTime)+(uncachedTransferTimeMSec-cachedTransferTimeMSec) as totalImprovement,\n(1-(cachedTurnAroundTime+cachedTransferTimeMSec)/(uncachedTurnAroundTime+uncachedTransferTimeMSec)) as totalPercentImprovement,\nreqHost,\nreqPath\nfrom ${ds2}\nwhere $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode IN (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus IN (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod IN (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType IN (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode IN (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll(reqPath IN (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP IN (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(UA IN (${UA:sqlstring}), $UA)\nAND isNotNull(reqHost)\nAND $__conditionalAll(country IN (${country:sqlstring}), $country)\ngroup by url,reqHost,reqPath\norder by count desc \nLIMIT 200",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Cached Status Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT  toString(statusCode),\ncount(*) as count\nFROM  ${ds2}\nwhere $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode IN (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus IN (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod IN (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType IN (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode IN (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll(reqPath IN (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP IN (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(UA IN (${UA:sqlstring}), $UA)\nand cacheStatus=1\nGROUP by statusCode\norder by count desc\nLIMIT 100",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Uncached Status Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT  toString(statusCode),\ncount(*) as count\nFROM  ${ds2}\nwhere $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode IN (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus IN (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod IN (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType IN (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode IN (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll(reqPath IN (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP IN (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(UA IN (${UA:sqlstring}), $UA)\nand cacheStatus=0\nGROUP by statusCode\norder by count desc\nLIMIT 100",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raw Logs",
     "type": "logs",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT toString(statusCode), UA,accLang,billingRegion,bytes,cacheStatus,cacheable,city,cliIP,country,\ncp,dnsLookupTimeMSec,edgeAttempts,edgeIP,errorCode,fileSizeBucket,lastByte,latency,maxAgeSec,objSize,originContentLen,\noverheadBytes,proto,queryStr,range,referer,reqEndTimeMSec,reqHost,reqId,reqMethod,reqPath,reqTimeSec,rspContentLen,rspContentType,securityRules,\nserverCountry,state,statusCode,streamId,tlsOverheadTimeMSec,tlsVersion,totalBytes,transferTimeMSec,turnAroundTimeMSec,\nuncompressedSize,version,xForwardedFor\nfrom ${ds2}\nWHERE $__timeFilter(reqTimeSec)\nAND $__conditionalAll( statusCode IN (${statusCode:sqlstring}), $statusCode)\nAND $__conditionalAll( reqHost IN (${reqHost:sqlstring}), $reqHost)\nAND $__conditionalAll( cacheStatus IN (${cacheStatus:sqlstring}), $cacheStatus)\nAND $__conditionalAll( reqMethod IN (${reqMethod:sqlstring}), $reqMethod)\nAND $__conditionalAll( rspContentType IN (${rspContentType:sqlstring}), $rspContentType)\nAND $__conditionalAll( errorCode IN (${errorCode:sqlstring}), $errorCode)\nAND $__conditionalAll(reqPath IN (${reqPath:sqlstring}), $reqPath)\nAND $__conditionalAll(cliIP IN (${cliIP:sqlstring}), $cliIP)\nAND $__conditionalAll(UA IN (${UA:sqlstring}), $UA)\nORDER BY reqTimeSec\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - rawlogs - ${__user.login}'",
       "selectedFormat": 2
      }
     ]
    }
   ]
  }
 ]
}