{
 "title": "Error Analysis",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds2",
    "query": "SELECT CONCAT((SELECT name FROM system.databases),'.', 'logs')"
   },
   {
    "name": "reqHost",
    "label": "Hostname",
    "query": "select reqHost from ${ds2}\nwhere $__timeFilter(reqTimeSec)\ngroup by reqHost \norder by count(reqHost) desc\nlimit 200"
   },
   {
    "name": "reqPath",
    "label": "Path Like",
    "query": "select reqPath from ${ds2}\nwhere $__timeFilter(reqTimeSec)\ngroup by reqPath \norder by count(reqHost) desc\nlimit 500"
   },
   {
    "name": "queryStr",
    "label": "Query Str Like",
    "query": "select queryStr from ${ds2}\nwhere $__timeFilter(reqTimeSec)\ngroup by queryStr \norder by count(reqHost) desc\nlimit 500"
   },
   {
    "name": "country",
    "label": "Country",
    "query": "select country from ${ds2}\nwhere $__timeFilter(reqTimeSec)\ngroup by country \norder by count(country) desc\nlimit 200"
   },
   {
    "name": "state",
    "label": "State",
    "query": "select state from ${ds2}\nwhere $__timeFilter(reqTimeSec)\ngroup by state order by count (state) desc\nlimit 200"
   },
   {
    "name": "city",
    "label": "City",
    "query": "select city from ${ds2}\nwhere $__timeFilter(reqTimeSec)\ngroup by city order by count(city) desc\nlimit 200"
   },
   {
    "name": "rspContentType",
    "label": "Content Type",
    "query": "select rspContentType from ${ds2}\nwhere $__timeFilter(reqTimeSec)\ngroup by rspContentType \norder by count(rspContentType) desc\nlimit 200"
   },
   {
    "name": "statusCode",
    "label": "HTTP Status Code",
    "query": "select statusCode from ${ds2}\nwhere $__timeFilter(reqTimeSec)\ngroup by statusCode\norder by count(statusCode) desc\nlimit 100"
   },
   {
    "name": "errorCode",
    "label": "Error Code",
    "query": "select errorCode from ${ds2}\nwhere $__timeFilter(reqTimeSec)\ngroup by errorCode\norder by count(errorCode) desc\nlimit 1000"
   },
   { "name": "referer", "label": "Referer" },
   {
    "name": "UA",
    "label": "User Agent",
    "query": "select UA from ${ds2}\nwhere $__timeFilter(reqTimeSec) \ngroup by UA order by count(UA) desc\nlimit 1000"
   },
   { "name": "treemapCells", "query": "${VAR_TREEMAPCELLS}" },
   { "name": "minErrorRate", "label": "Min Error Rate", "query": ".00" },
   {
    "name": "treeMapGroupBy",
    "label": "treeMapGroupBy",
    "query": "Hostname : reqHost , Path : reqPath , Query Str : queryStr , Client IP : cliIP , UA : UA , Country : country , State : state , City : city , referer : referer , Content Type : rspContentType , AS Org : akamai_geo('org'\\,cliIP)"
   },
   { "name": "secRulesLike", "label": "secRulesLike", "query": "%399%" }
  ]
 },
 "panels": [
  {
   "title": "Total requests - Summary",
   "type": "stat",
   "description": "Summary graphs don't accept filters on \nreqPath, queryString (user, session, project)",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  count() as count\nFROM ${ds2} \nwhere $__timeFilter(reqTimeSec)\nand $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost})\nand $__conditionalAll(reqPath in (${reqPath:sqlstring}), ${reqPath})\nand $__conditionalAll(queryStr in (${queryStr:sqlstring}), ${queryStr})\nand $__conditionalAll(country in (${country:sqlstring}), ${country})\nand $__conditionalAll(state in (${state:sqlstring}), ${state})\nand $__conditionalAll(city in (${city:sqlstring}), ${city})\nand $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nand $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode})\nand $__conditionalAll(errorCode in (${errorCode:sqlstring}), ${errorCode})\nand if (empty('${referer}'),true,referer like '${referer}')\nand $__conditionalAll(UA in (${UA:sqlstring}), ${UA})\nLIMIT 100",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Requests Over Time ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n toString(statusCode) as HTTP_Status_Code, \n $__timeInterval(reqTimeSec) as time, \n count(*) as http\nFROM ${ds2}\nwhere $__timeFilter(reqTimeSec)\nand $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost})\nand $__conditionalAll(reqPath in (${reqPath:sqlstring}), ${reqPath})\nand $__conditionalAll(queryStr in (${queryStr:sqlstring}), ${queryStr})\nand $__conditionalAll(country in (${country:sqlstring}), ${country})\nand $__conditionalAll(state in (${state:sqlstring}), ${state})\nand $__conditionalAll(city in (${city:sqlstring}), ${city})\nand $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nand $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode})\nand $__conditionalAll(errorCode in (${errorCode:sqlstring}), ${errorCode})\nand if (empty('${referer}'),true,referer like '${referer}')\nand $__conditionalAll(UA in (${UA:sqlstring}), ${UA})\nGROUP BY HTTP_Status_Code, time ORDER BY time\n\n",
     "selectedFormat": 4
    }
   ]
  },
  { "title": "Error Treemaps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "HTTP Error Rate for top ${treemapCells} ${treeMapGroupBy} (excludes error rates less than ${minErrorRate})",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT  \n  coalesce(${treeMapGroupBy},'-') as item,\n  /*If path may contain the word 'undefined' then use this:   replaceOne(ifNull(concat(reqHost,reqPath),'-'),'undefined','undefine_d') as reqPath, */\n  count(*)  as count,\n  countIf(statusCode>=400)/count(statusCode) as errorRate\nFROM  ${ds2}\nwhere $__timeFilter(reqTimeSec)\nand $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost})\nand $__conditionalAll(reqPath in (${reqPath:sqlstring}), ${reqPath})\nand $__conditionalAll(queryStr in (${queryStr:sqlstring}), ${queryStr})\nand $__conditionalAll(country in (${country:sqlstring}), ${country})\nand $__conditionalAll(state in (${state:sqlstring}), ${state})\nand $__conditionalAll(city in (${city:sqlstring}), ${city})\nand $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nand $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode})\nand $__conditionalAll(errorCode in (${errorCode:sqlstring}), ${errorCode})\nand if (empty('${referer}'),true,referer like '${referer}')\nand $__conditionalAll(UA in (${UA:sqlstring}), ${UA})\nGROUP by item\nhaving errorRate>=${minErrorRate}\norder by count desc\nLIMIT ${treemapCells}",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Error Rate for top ${treemapCells} ${treeMapGroupBy} (Excludes error rates below ${minErrorRate})",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT  \n  coalesce(${treeMapGroupBy},'-') as item,\n  /*If path may contain the word 'undefined' then use this:   replaceOne(ifNull(concat(reqHost,reqPath),'-'),'undefined','undefine_d') as reqPath, */\n  count(*)  as count,\n  countIf(isNotNull(errorCode))/count(*) as percentError\nFROM  ${ds2}\nwhere $__timeFilter(reqTimeSec)\nand $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost})\nand $__conditionalAll(reqPath in (${reqPath:sqlstring}), ${reqPath})\nand $__conditionalAll(queryStr in (${queryStr:sqlstring}), ${queryStr})\nand $__conditionalAll(country in (${country:sqlstring}), ${country})\nand $__conditionalAll(state in (${state:sqlstring}), ${state})\nand $__conditionalAll(city in (${city:sqlstring}), ${city})\nand $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nand $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode})\nand $__conditionalAll(errorCode in (${errorCode:sqlstring}), ${errorCode})\nand if (empty('${referer}'),true,referer like '${referer}')\nand $__conditionalAll(UA in (${UA:sqlstring}), ${UA})\nGROUP by item\nhaving percentError>=${minErrorRate}\norder by count desc\nLIMIT ${treemapCells}",
     "selectedFormat": 4
    }
   ]
  },
  { "title": "Piecharts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Unique Resources",
   "type": "stat",
   "description": "Overall count of unique userIDs where a userID is first match in the queryString on regex: /id=(ac\\d+)/",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  count(distinct(reqPath)) \nFROM  ${ds2} \nwhere $__timeFilter(reqTimeSec)\nand $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost})\nand $__conditionalAll(reqPath in (${reqPath:sqlstring}), ${reqPath})\nand $__conditionalAll(queryStr in (${queryStr:sqlstring}), ${queryStr})\nand $__conditionalAll(country in (${country:sqlstring}), ${country})\nand $__conditionalAll(state in (${state:sqlstring}), ${state})\nand $__conditionalAll(city in (${city:sqlstring}), ${city})\nand $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nand $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode})\nand $__conditionalAll(errorCode in (${errorCode:sqlstring}), ${errorCode})\nand if (empty('${referer}'),true,referer like '${referer}')\nand $__conditionalAll(UA in (${UA:sqlstring}), ${UA})\nLIMIT 100",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "piechart",
   "description": "Number of requests per streaming format",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT toString(statusCode),\ncount(*) as count\nFROM  ${ds2}\nwhere $__timeFilter(reqTimeSec)\nand $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost})\nand $__conditionalAll(reqPath in (${reqPath:sqlstring}), ${reqPath})\nand $__conditionalAll(queryStr in (${queryStr:sqlstring}), ${queryStr})\nand $__conditionalAll(country in (${country:sqlstring}), ${country})\nand $__conditionalAll(state in (${state:sqlstring}), ${state})\nand $__conditionalAll(city in (${city:sqlstring}), ${city})\nand $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nand $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode})\nand $__conditionalAll(errorCode in (${errorCode:sqlstring}), ${errorCode})\nand if (empty('${referer}'),true,referer like '${referer}')\nand $__conditionalAll(UA in (${UA:sqlstring}), ${UA})\ngroup by statusCode\norder by count desc\nLIMIT 100",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Error Codes",
   "type": "piechart",
   "description": "Error codes per request",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT toString(errorCode),\ncount(*) as count\nFROM  ${ds2}\nwhere $__timeFilter(reqTimeSec)\nand $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost})\nand $__conditionalAll(reqPath in (${reqPath:sqlstring}), ${reqPath})\nand $__conditionalAll(queryStr in (${queryStr:sqlstring}), ${queryStr})\nand $__conditionalAll(country in (${country:sqlstring}), ${country})\nand $__conditionalAll(state in (${state:sqlstring}), ${state})\nand $__conditionalAll(city in (${city:sqlstring}), ${city})\nand $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nand $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode})\nand $__conditionalAll(errorCode in (${errorCode:sqlstring}), ${errorCode})\nand if (empty('${referer}'),true,referer like '${referer}')\nand $__conditionalAll(UA in (${UA:sqlstring}), ${UA})\ngroup by errorCode\norder by count desc\nLIMIT 100",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Unique IPs Overall",
   "type": "stat",
   "description": "Overall count of unique Client IPs in this time period",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  count(distinct(cliIP)) \nFROM  ${ds2} \nwhere $__timeFilter(reqTimeSec)\nand $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost})\nand $__conditionalAll(reqPath in (${reqPath:sqlstring}), ${reqPath})\nand $__conditionalAll(queryStr in (${queryStr:sqlstring}), ${queryStr})\nand $__conditionalAll(country in (${country:sqlstring}), ${country})\nand $__conditionalAll(state in (${state:sqlstring}), ${state})\nand $__conditionalAll(city in (${city:sqlstring}), ${city})\nand $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nand $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode})\nand $__conditionalAll(errorCode in (${errorCode:sqlstring}), ${errorCode})\nand if (empty('${referer}'),true,referer like '${referer}')\nand $__conditionalAll(UA in (${UA:sqlstring}), ${UA})\nLIMIT 100",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Countries",
   "type": "piechart",
   "description": "Number of requests per streaming format",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT country,\ncount(*) as count\nFROM  ${ds2}\nwhere $__timeFilter(reqTimeSec)\nand $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost})\nand $__conditionalAll(reqPath in (${reqPath:sqlstring}), ${reqPath})\nand $__conditionalAll(queryStr in (${queryStr:sqlstring}), ${queryStr})\nand $__conditionalAll(country in (${country:sqlstring}), ${country})\nand $__conditionalAll(state in (${state:sqlstring}), ${state})\nand $__conditionalAll(city in (${city:sqlstring}), ${city})\nand $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nand $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode})\nand $__conditionalAll(errorCode in (${errorCode:sqlstring}), ${errorCode})\nand if (empty('${referer}'),true,referer like '${referer}')\nand $__conditionalAll(UA in (${UA:sqlstring}), ${UA})\ngroup by country\norder by count desc\nLIMIT 100",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Resources",
   "type": "piechart",
   "description": "Number of requess per channel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT reqPath,\ncount(*) as count\nFROM  ${ds2}\nwhere $__timeFilter(reqTimeSec)\nand $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost})\nand $__conditionalAll(reqPath in (${reqPath:sqlstring}), ${reqPath})\nand $__conditionalAll(queryStr in (${queryStr:sqlstring}), ${queryStr})\nand $__conditionalAll(country in (${country:sqlstring}), ${country})\nand $__conditionalAll(state in (${state:sqlstring}), ${state})\nand $__conditionalAll(city in (${city:sqlstring}), ${city})\nand $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nand $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode})\nand $__conditionalAll(errorCode in (${errorCode:sqlstring}), ${errorCode})\nand if (empty('${referer}'),true,referer like '${referer}')\nand $__conditionalAll(UA in (${UA:sqlstring}), ${UA})\ngroup by reqPath\norder by count desc\nLIMIT 100",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Content Types",
   "type": "piechart",
   "description": "Number of requests per streaming format",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT rspContentType,\ncount(*) as count\nFROM  ${ds2}\nwhere $__timeFilter(reqTimeSec)\nand $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost})\nand $__conditionalAll(reqPath in (${reqPath:sqlstring}), ${reqPath})\nand $__conditionalAll(queryStr in (${queryStr:sqlstring}), ${queryStr})\nand $__conditionalAll(country in (${country:sqlstring}), ${country})\nand $__conditionalAll(state in (${state:sqlstring}), ${state})\nand $__conditionalAll(city in (${city:sqlstring}), ${city})\nand $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nand $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode})\nand $__conditionalAll(errorCode in (${errorCode:sqlstring}), ${errorCode})\nand if (empty('${referer}'),true,referer like '${referer}')\nand $__conditionalAll(UA in (${UA:sqlstring}), ${UA})\ngroup by rspContentType\norder by count desc\nLIMIT 100",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Referer",
   "type": "table",
   "description": "Number of requess per channel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT referer,\ncount(*) as count\nFROM  ${ds2}\nwhere $__timeFilter(reqTimeSec)\nand $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost})\nand $__conditionalAll(reqPath in (${reqPath:sqlstring}), ${reqPath})\nand $__conditionalAll(queryStr in (${queryStr:sqlstring}), ${queryStr})\nand $__conditionalAll(country in (${country:sqlstring}), ${country})\nand $__conditionalAll(state in (${state:sqlstring}), ${state})\nand $__conditionalAll(city in (${city:sqlstring}), ${city})\nand $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nand $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode})\nand $__conditionalAll(errorCode in (${errorCode:sqlstring}), ${errorCode})\nand if (empty('${referer}'),true,referer like '${referer}')\nand $__conditionalAll(UA in (${UA:sqlstring}), ${UA})\ngroup by referer\norder by count desc\nLIMIT 100",
     "selectedFormat": 4
    }
   ]
  },
  { "title": "Security Flags Treemap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Security Rate for top ${treemapCells} ${treeMapGroupBy} (Excludes error rates below ${minErrorRate})",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT  \n  coalesce(${treeMapGroupBy},'-') as item,\n  /*If path may contain the word 'undefined' then use this:   replaceOne(ifNull(concat(reqHost,reqPath),'-'),'undefined','undefine_d') as reqPath, */\n  count(*)  as count,\n  countIf(securityRules like '${secRulesLike}')/count(*) as percentError\nFROM  ${ds2}\nwhere $__timeFilter(reqTimeSec)\nand $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost})\nand $__conditionalAll(reqPath in (${reqPath:sqlstring}), ${reqPath})\nand $__conditionalAll(queryStr in (${queryStr:sqlstring}), ${queryStr})\nand $__conditionalAll(country in (${country:sqlstring}), ${country})\nand $__conditionalAll(state in (${state:sqlstring}), ${state})\nand $__conditionalAll(city in (${city:sqlstring}), ${city})\nand $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nand $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode})\nand $__conditionalAll(errorCode in (${errorCode:sqlstring}), ${errorCode})\nand if (empty('${referer}'),true,referer like '${referer}')\nand $__conditionalAll(UA in (${UA:sqlstring}), ${UA})\nGROUP by item\nhaving percentError>=${minErrorRate}\norder by count desc\nLIMIT ${treemapCells}",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Top Security Rules",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT  \n  securityRules,\n  /*If path may contain the word 'undefined' then use this:   replaceOne(ifNull(concat(reqHost,reqPath),'-'),'undefined','undefine_d') as reqPath, */\n  count(*)  as count\nFROM  ${ds2}\nwhere $__timeFilter(reqTimeSec)\nand $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost})\nand $__conditionalAll(reqPath in (${reqPath:sqlstring}), ${reqPath})\nand $__conditionalAll(queryStr in (${queryStr:sqlstring}), ${queryStr})\nand $__conditionalAll(country in (${country:sqlstring}), ${country})\nand $__conditionalAll(state in (${state:sqlstring}), ${state})\nand $__conditionalAll(city in (${city:sqlstring}), ${city})\nand $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nand $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode})\nand $__conditionalAll(errorCode in (${errorCode:sqlstring}), ${errorCode})\nand if (empty('${referer}'),true,referer like '${referer}')\nand if (empty('${secRulesLike}'),true,securityRules like '${secRulesLike}')\nand $__conditionalAll(UA in (${UA:sqlstring}), ${UA})\nGROUP by securityRules\norder by count desc\nLIMIT ${treemapCells}",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raw Logs",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT  concat(toString(statusCode),'-',reqHost,reqPath) , concat(reqHost,reqPath) as URL, * except (statusCode, unknown)\nFROM ${ds2} \nwhere $__timeFilter(reqTimeSec)\nand $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost})\nand $__conditionalAll(reqPath in (${reqPath:sqlstring}), ${reqPath})\nand $__conditionalAll(queryStr in (${queryStr:sqlstring}), ${queryStr})\nand $__conditionalAll(country in (${country:sqlstring}), ${country})\nand $__conditionalAll(state in (${state:sqlstring}), ${state})\nand $__conditionalAll(city in (${city:sqlstring}), ${city})\nand $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nand $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode})\nand $__conditionalAll(errorCode in (${errorCode:sqlstring}), ${errorCode})\nand if (empty('${referer}'),true,referer like '${referer}')\nand $__conditionalAll(UA in (${UA:sqlstring}), ${UA})\nand if (empty('${secRulesLike}'),true,securityRules like '${secRulesLike}')\nLIMIT 100",
       "selectedFormat": 4
      }
     ]
    }
   ]
  }
 ]
}