{
 "title": "Performance Analysis",
 "time": { "from": "2024-04-15T22:22:03.318Z", "to": "2024-04-16T00:32:17.106Z" },
 "templating": {
  "list": [
   {
    "name": "ds2",
    "query": "SELECT CONCAT((SELECT name FROM system.databases),'.', 'logs')"
   },
   { "name": "reqId", "label": "Request ID" },
   {
    "name": "metric",
    "label": "TreeMaps Timer",
    "query": "Transfer Time : transferTimeMSec , Turn Around Time : turnAroundTimeMSec, DNS Time : dnsLookupTimeMSec, Total Bytes : totalBytes"
   },
   {
    "name": "AggType",
    "query": "Average : avg , Median :  quantile(0.5) , P75 : quantile(0.75) , P90 : quantile(0.90) , P95 : quantile(0.95) , P99 : quantile(0.99)"
   },
   {
    "name": "rspContentType",
    "label": "Content Type",
    "query": "select rspContentType \nfrom ${ds2}\nwhere $__timeFilter(reqTimeSec)\ngroup by rspContentType\norder by count (rspContentType) desc"
   },
   {
    "name": "reqHost",
    "label": "Hostname",
    "query": "select reqHost from ${ds2}\nwhere $__timeFilter(reqTimeSec)\ngroup by reqHost\norder by count (reqHost) desc"
   },
   {
    "name": "statusCode",
    "label": "Status Code",
    "query": "select statusCode from ${ds2}\nwhere $__timeFilter(reqTimeSec)\ngroup by statusCode\norder by count (statusCode) desc"
   },
   {
    "name": "country",
    "label": "Country",
    "query": "select country from ${ds2}\nwhere $__timeFilter(reqTimeSec)\ngroup by country\norder by count (country) desc"
   },
   {
    "name": "cacheStatus",
    "label": "Cache Status",
    "query": "select cacheStatus from ${ds2}\nwhere $__timeFilter(reqTimeSec)\ngroup by cacheStatus\norder by count (cacheStatus) desc"
   },
   { "name": "pathLike", "label": "Path Like" }
  ]
 },
 "panels": [
  { "title": "Performance Timers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Press 'v'",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "# INFO\nPress 'v' to enlarge.\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
   }
  },
  {
   "title": "Performance Timer Values (${AggType})",
   "type": "timeseries",
   "description": "Timers description\n* tls: After the TCP connection is established, there will be a handshake to establish the TLS connection. This measures how long it takes to establish that TLS connection\n* reqEndTime: After the TLS connection is established, the request is sent. This measures how long it takes to send the request.\n* DNS Time: After the request is sent, the edge server may need to lookup the IP address of the origin. When that happens, this measures how long it took.\n* turnAroundTime: After the request was received, how long until Akamai sent back the first byte of the response.\n* transferTime: If there are multiple TCP packets in the response, how long from the first packet send until the last packet sent (download time)",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT  $__timeInterval(reqTimeSec) as time,\n${AggType}(tlsOverheadTimeMSec) as tls,\n${AggType}(transferTimeMSec) as transferTime,\n${AggType}(dnsLookupTimeMSec) as dnsTime,\n${AggType}(turnAroundTimeMSec) as turnAroundTime,\n${AggType}(reqEndTimeMSec) as endTime\nFROM ${ds2}\n WHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\ngroup by time\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Total Requests ",
   "type": "stat",
   "description": "Shows how many total requests were sent in this time period",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT  $__timeInterval(reqTimeSec) as time,\ncount(*) as count\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\ngroup by time\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Performance Timer Values (${AggType})",
   "type": "stat",
   "description": "Timers description\n* tls: After the TCP connection is established, there will be a handshake to establish the TLS connection. This measures how long it takes to establish that TLS connection\n* reqEndTime: After the TLS connection is established, the request is sent. This measures how long it takes to send the request.\n* DNS Time: After the request is sent, the edge server may need to lookup the IP address of the origin. When that happens, this measures how long it took.\n* turnAroundTime: After the request was received, how long until Akamai sent back the first byte of the response.\n* transferTime: If there are multiple TCP packets in the response, how long from the first packet send until the last packet sent (download time)",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "repeat": "AggType",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \n${AggType}(tlsOverheadTimeMSec) as tls,\n${AggType}(reqEndTimeMSec) as reqEndTime,\n${AggType}(dnsLookupTimeMSec) as dnsTime,\n${AggType}(turnAroundTimeMSec) as turnAroundTime,\n${AggType}(transferTimeMSec) as transferTime\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Performance Timer Frequency",
   "type": "stat",
   "description": "What percentage of requests incurred additional time for each of these timers:\n* tls : If a request is sent on an already established TLS connection, then the request will have no TLS time\n* DNS Time: If the IP address of all necessary servers are fresh in DNS cache, then there will be no DNS time incurred\n* transferTime: If the entire response is sent in the first TCP packet, then there will be now transferTime",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \ncountIf(tlsOverheadTimeMSec>0)/count(*) as tls,\ncountIf(reqEndTimeMSec>0)/count(*) as endTime,\ncountIf(dnsLookupTimeMSec>0)/count(*) as dnsTime,\ncountIf(turnAroundTimeMSec>0)/count(*) as turnAroundTime,\ncountIf(transferTimeMSec>0)/count(*) as transferTime\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Treemaps: ${metric} Across Various Dimensions (select different 'Treemaps Timer' from drop-down)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "${metric} by Country (${AggType})",
     "type": "marcusolsson-treemap-panel",
     "description": "Most common content types at top.",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 23 },
     "targets": [
      {
       "rawSql": "SELECT  coalesce(country,'-') as metric, $AggType($metric) as agg_value, count(*) as count\nFROM  ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\ngroup by metric\norder by $AggType($metric)  desc\nLIMIT 500",
       "selectedFormat": 4
      }
     ]
    },
    {
     "title": "${metric} by Content Type (${AggType})",
     "type": "marcusolsson-treemap-panel",
     "description": "Most common content types at top.",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 23 },
     "targets": [
      {
       "rawSql": "SELECT  coalesce(rspContentType,'-') as metric, $AggType($metric) as agg_value, count(*) as count\nFROM  ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\ngroup by metric\norder by $AggType($metric)  desc\nLIMIT 500",
       "selectedFormat": 4
      }
     ]
    },
    {
     "title": "${metric} by Hostname (${AggType})",
     "type": "marcusolsson-treemap-panel",
     "description": "Most common content types at top.",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 23 },
     "targets": [
      {
       "rawSql": "SELECT  coalesce(reqHost,'-') as metric, $AggType($metric) as agg_value, count(*) as count\nFROM  ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\ngroup by metric\norder by $AggType($metric)  desc\nLIMIT 500",
       "selectedFormat": 4
      }
     ]
    },
    {
     "title": "${metric} by Path (${AggType})",
     "type": "marcusolsson-treemap-panel",
     "description": "Most common content types at top.",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 34 },
     "targets": [
      {
       "rawSql": "SELECT  coalesce(reqPath,'-') as metric, $AggType($metric) as agg_value, count(*) as count\nFROM  ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\ngroup by metric\norder by $AggType($metric)  desc\nLIMIT 1000",
       "selectedFormat": 4
      }
     ]
    },
    {
     "title": "${metric} by Status Code (${AggType})",
     "type": "marcusolsson-treemap-panel",
     "description": "Most common content types at top.",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 34 },
     "targets": [
      {
       "rawSql": "SELECT  coalesce(toString(statusCode),'-') as metric, $AggType($metric) as agg_value, count(*) as count\nFROM  ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\ngroup by metric\norder by $AggType($metric)  desc\nLIMIT 1000",
       "selectedFormat": 4
      }
     ]
    },
    {
     "title": "${metric} by Cache Status (${AggType})",
     "type": "marcusolsson-treemap-panel",
     "description": "Most common content types at top.",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 34 },
     "targets": [
      {
       "rawSql": "SELECT  coalesce(toString(cacheStatus),'-') as metric, \n$AggType($metric) as agg_value, count(*) as count\nFROM  ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\ngroup by metric\norder by $AggType($metric)  desc\nLIMIT 1000",
       "selectedFormat": 4
      }
     ]
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raw Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "rawSql": "SELECT toString(statusCode), UA,accLang,billingRegion,bytes,cacheStatus,cacheable,city,cliIP,country,\ncp,dnsLookupTimeMSec,edgeAttempts,edgeIP,errorCode,fileSizeBucket,lastByte,latency,maxAgeSec,objSize,originContentLen,\noverheadBytes,proto,queryStr,range,referer,reqEndTimeMSec,reqHost,reqId,reqMethod,reqPath,reqTimeSec,rspContentLen,securityRules,\nserverCountry,state,statusCode,streamId,tlsOverheadTimeMSec,tlsVersion,totalBytes,transferTimeMSec,turnAroundTimeMSec,\nuncompressedSize,version,xForwardedFor\nfrom ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\nLIMIT 100\nSETTINGS hdx_query_max_execution_time=60, hdx_query_admin_comment='akamai - rawlogs - ${__user.login}'",
       "selectedFormat": 4
      }
     ]
    }
   ]
  },
  {
   "title": "Edge Info (from Breadcrumbs)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "# Edge DNS Lookups",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n    countIf(Edge_DNSLookupTime>0) as count,\n    $__timeInterval(reqTimeSec) as time\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\nGROUP BY time\nLIMIT 100"
      }
     ]
    },
    {
     "title": "Edge_DNSLookupTime (average)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n    avg(Edge_DNSLookupTime) Edge_DNSLookupTime,\n    $__timeInterval(reqTimeSec) as time\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\nGROUP BY time\nLIMIT 100"
      }
     ]
    },
    {
     "title": "Edge_RequestEndTime (average)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n    avg(Edge_RequestEndTime) Edge_RequestEndTime,\n    $__timeInterval(reqTimeSec) as time\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\nGROUP BY time\nLIMIT 100"
      }
     ]
    },
    {
     "title": "# Edge_TurnAroundTime (count)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n    count(Edge_TurnAroundTime) as count_EdgeTurnaroundTime,\n    $__timeInterval(reqTimeSec) as time\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\nand Edge_TurnAroundTime>0\nGROUP BY time\n"
      }
     ]
    },
    {
     "title": "Edge_TurnAroundTime (average)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 15, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n    avg(Edge_TurnAroundTime) Edge_TurnAroundTime,\n    $__timeInterval(reqTimeSec) as time\nFROM ${ds2}\nWHERE   ( reqTimeSec  >= $__fromTime AND reqTimeSec <= $__toTime ) \nGROUP BY time\n"
      }
     ]
    },
    {
     "title": "Edge_IP",
     "type": "table",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT \n    Edge_IP,\n    count(*) as count\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\nGROUP BY Edge_IP\nORDER BY count DESC\nlimit 20\n"
      }
     ]
    }
   ]
  },
  { "title": "Origin Info (from Breadcrumbs)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "# Origin_DNSLookupTime ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    avg(Origin_DNSLookupTime) Origin_DNS_Lookup,\n    $__timeInterval(reqTimeSec) as time\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\nGROUP BY time\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Origin_DNSLookupTime (average)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    avg(Origin_DNSLookupTime) Origin_DNS_Lookup,\n    $__timeInterval(reqTimeSec) as time\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\nGROUP BY time\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Origin_RequestEndTime (average)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    avg(Origin_RequestEndTime) Origin_RequestEndTime,\n    $__timeInterval(reqTimeSec) as time\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\nGROUP BY time\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Origin_TurnAroundTime (average)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    avg(Origin_TurnAroundTime) Origin_TurnAroundTime,\n    $__timeInterval(reqTimeSec) as time\nFROM ${ds2}\nWHERE   ( reqTimeSec  >= $__fromTime AND reqTimeSec <= $__toTime ) \nGROUP BY time\n"
    }
   ]
  },
  {
   "title": "% Requests with Origin Request",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    countIf(Origin_TurnAroundTime,Origin_TurnAroundTime>0) /countIf(Edge_TurnAroundTime,Edge_TurnAroundTime>0 ) as percent_origin_requests,\n    $__timeInterval(reqTimeSec) as time\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\nGROUP BY time\n"
    }
   ]
  },
  {
   "title": "Origin IP",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n    Origin_IP,\n    count(*) as count\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\nGROUP BY Origin_IP\nORDER BY count DESC\nlimit 20\n"
    }
   ]
  },
  {
   "title": "Parent Info (from Breadcrumbs)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Parent_DNSLookupTime (average)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n    avg(Parent_DNSLookupTime) Parent_DNSLookupTime,\n    $__timeInterval(reqTimeSec) as time\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\nGROUP BY time\nLIMIT 100"
      }
     ]
    },
    {
     "title": "Parent_RequestEndTime (average)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n    avg(Parent_RequestEndTime) Parent_RequestEndTime,\n    $__timeInterval(reqTimeSec) as time\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\nGROUP BY time\nLIMIT 100"
      }
     ]
    },
    {
     "title": "Parent_TurnAroundTime (average)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 10, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n    avg(Parent_TurnAroundTime) Parent_TurnAroundTime,\n    $__timeInterval(reqTimeSec) as time\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\nGROUP BY time\nLIMIT 100"
      }
     ]
    },
    {
     "title": "% Requests with Parent Request",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 15, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n    countIf(Parent_TurnAroundTime,Parent_TurnAroundTime>0)/countIf(Edge_TurnAroundTime,Edge_TurnAroundTime>0),\n    $__timeInterval(reqTimeSec) as time\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\nGROUP BY time\n"
      }
     ]
    },
    {
     "title": "Parent_IP",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT \n    Parent_IP,\n    count(*) as count\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\nGROUP BY Parent_IP\nORDER BY count DESC\nlimit 20\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Peer Info (from Breadcrumbs)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Peer_DNSLookupTime (average)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n    avg(Peer_DNSLookupTime) Peer_DNSLookupTime,\n    $__timeInterval(reqTimeSec) as time\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\nGROUP BY time\nLIMIT 100"
      }
     ]
    },
    {
     "title": "Peer_RequestEndTime (average)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n    avg(Peer_RequestEndTime) Peer_RequestEndTime,\n    $__timeInterval(reqTimeSec) as time\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\nGROUP BY time\nLIMIT 100"
      }
     ]
    },
    {
     "title": "Peer_TurnAroundTime (average)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 10, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n    avg(Peer_TurnAroundTime) Peer_TurnAroundTime,\n    $__timeInterval(reqTimeSec) as time\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\nGROUP BY time\nLIMIT 100"
      }
     ]
    },
    {
     "title": "% Requests with Peer Request",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 15, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n    countIf(Peer_TurnAroundTime,Peer_TurnAroundTime>0)/ countIf(Edge_TurnAroundTime,Edge_TurnAroundTime>0) as percentWithPeerRequest,\n    $__timeInterval(reqTimeSec) as time\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\nGROUP BY time\n"
      }
     ]
    },
    {
     "title": "Peer_IP",
     "type": "table",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT \n    Peer_IP,\n    count(*) as count\nFROM ${ds2}\nWHERE   $__timeFilter(reqTimeSec) \nAND $__conditionalAll(rspContentType in (${rspContentType:sqlstring}), ${rspContentType})\nAND $__conditionalAll(reqHost in (${reqHost:sqlstring}), ${reqHost}})\nAND $__conditionalAll(statusCode in (${statusCode:sqlstring}), ${statusCode}})\nAND $__conditionalAll(country in (${country:sqlstring}), ${country}})\nAND $__conditionalAll(cacheStatus in (${cacheStatus:sqlstring}), ${cacheStatus}})\nAND if ( empty('${pathLike:text}') , true, reqPath like '${pathLike}' )\nAND if ( empty('${reqId:text}') , true, reqId = '${reqId}' )\nGROUP BY Peer_IP\nORDER BY count DESC\nlimit 20\n"
      }
     ]
    }
   ]
  }
 ]
}